targets:
  $default:
    builders:
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          - "lib/core/model/**.dart"
          - "lib/core/service/fcm/**.dart"
      isar_generator|isar_generator:
        enabled: true
        generate_for:
          - "lib/core/model/**.dart"
      freezed: 
        enabled: true
        generate_for:
          - "lib/core/model/sdui/**.dart"
        options: 
          copy_with: false
          map: false
          when:
            when: false
            maybe_when: false
            when_or_null: false
