targets:
  $default:
    builders:
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          - "lib/core/model/**.dart"
          - "lib/core/service/fcm/**.dart"
          - "lib/core/service/feature_flag_service/types.dart"
          - "lib/feature/shorts/src/service/**.dart"

      isar_generator|isar_generator:
        enabled: true
        generate_for:
          - "lib/core/model/**.dart"
      freezed: 
        enabled: true
        generate_for:
          - "lib/core/model/sdui/**.dart"
          - "lib/feature/shorts/src/bloc/**.dart"
        options: 
          copy_with: true
          map: true
          when:
            when: false
            maybe_when: false
            when_or_null: false
