class CreateUser {
  static const String path = 'api/createUser';
  static const String fldMobile = 'mobile';
  static const String fldID = 'uid';
  static const String fldUserName = 'uname';
  static const String fldStateId = 'stateid';

  static const String resStatusCode = 'statusCode';
}

class GetRates {
  static const String path = 'api/rates';

  static const String resRates = 'rates';
  static const String resGoldBuyRate = 'gBuy';
  static const String resSilverBuyRate = 'sBuy';
  static const String resGoldSellRate = 'gSell';
  static const String resSilverSellRate = 'sSell';
  static const String resBlockId = 'blockId';
}

/**
 * {"quantity":"0.1051","totalAmount":"500.00","preTaxAmount":"485.44",
 * "metalType":"gold","rate":"4614.80","uniqueId":"fello_AMVPL5308BX",
 * "transactionId":"FL524816147746361350085490","userName":"shouryaditya.ray.lala",
 * "merchantTransactionId":"abcd-1342234-zxsweesa","mobileNumber":"9986643444",
 * "goldBalance":"0.4204","silverBalance":"0.0000","taxes":{"totalTaxAmount":"14.56",
 * "taxSplit":[{"type":"CGST","taxPerc":"1.50","taxAmount":"7.28"},{"type":"SGST",
 * "taxPerc":"1.50","taxAmount":"7.28"}]},"invoiceNumber":"GFL032104"}
 *
 * {"quantity":"0.0231","totalAmount":"109.00","preTaxAmount":"105.83",
 * "metalType":"gold","rate":"4577.90","uniqueId":"fello77AMVPL5308B",
 * "transactionId":"FL135416161312646250086020","userName":"felloGYyzamGPhSnadOXVpElZzuwoYWm",
 * "merchantTransactionId":"bQirAX5QnaZ2adQKYq9svY","mobileNumber":"9986643444",
 * "goldBalance":"0.0684","silverBalance":"0.0000","taxes":{"totalTaxAmount":"3.17",
 * "taxSplit":[{"type":"CGST","taxPerc":"1.50","taxAmount":"1.59"},
 * {"type":"SGST","taxPerc":"1.50","taxAmount":"1.59"}]},"invoiceNumber":"GFL032127"}
 * */
class SubmitGoldPurchase {
  static const String path = 'api/submitGoldPurchase';
  static const String fldLockPrice = 'lockprice';
  static const String fldAmount = 'amount';
  static const String fldMobile = 'mobile';
  static const String fldUid = 'uid';
  static const String fldPaymode = 'paymode';
  static const String fldUsername = 'uname';
  static const String fldStateId = 'stateid';
  static const String fldBlockId = 'blockid';
  static const String fldMerchantTranId = 'merchantTranId';

  static const String resTranId =
      'merchantTransactionId'; //generated by our server
  static const String resGoldBalance = 'goldBalance';
  static const String resPreTaxAmount = 'preTaxAmount';
  static const String resAugTranId = 'transactionId'; //generated by augmont
}

/**
 * {"merchantId":11055,"quantity":"0.0157","totalAmount":"70.00",
 * "preTaxAmount":"70.00","metalType":"gold","rate":"4441.50",
 * "uniqueId":"fello_AMVPL5308B","transactionId":"FL535216147821702650085173",
 * "userName":"shouryaditya.ray.lala","merchantTransactionId":"defg-2323dazxpst",
 * "mobileNumber":"9986643444","goldBalance":"0.0869","silverBalance":"0.0000",
 * "bankInfo":{"accountName":"INDUSIND BANK","accountNumber":"159986643444",
 * "ifscCode":"INDB0001394"}}
 * */
class SubmitGoldSell {
  static const String path = 'api/submitGoldQntSell';
  static const String fldLockPrice = 'lockPrice';
  static const String fldAmount = 'amount';
  static const String fldQuantity = 'quantity';
  static const String fldMobile = 'mobile';
  static const String fldAugmontUid = 'uid';
  static const String fldUsername = 'uname';
  static const String fldAccHolderName = 'acctname';
  static const String fldAccNo = 'accno';
  static const String fldIfsc = 'ifsc';
  static const String fldBlockId = 'blockId';
  static const String fldMerchantTranId = 'merchantTranId';

  static const String resTranId = 'merchantTransactionId';
  static const String resGoldBalance = 'goldBalance';
  static const String resPreTaxAmount = 'preTaxAmount';
  static const String resAugTranId = 'transactionId';
}

class Passbook {
  static const String path = 'api/passbook';
  static const String fldAugmontUid = 'uid';

  static const String resGoldGrams = 'goldGrms';
  static const String resSilverGrams = 'silverGrms';
}

/**
 * {
    "invoiceNumber": "GFL022102",
    "userInfo": {"name": "shouryaditya.ray.lala","address": null,"city": null,
    "state": "Manipur","pincode": null,"email": null,"mobileNumber": "9986643444",
    "uniqueId": "fello_AMVPL5308B"},
    "transactionId": "FL763316143515330650085173","quantity": "0.1026",
    "metalType": "gold","hsnCode": "71141110","rate": "4727.40","unitType": "Gram",
    "grossAmount": "485.44","netAmount": "500.00",
    "taxes": {"totalTaxAmount": "14.56",
    "taxSplit": [{"type": "CGST","taxPerc": "1.50","taxAmount": "7.28"},
    {"type": "SGST","taxPerc": "1.50","taxAmount": "7.28"},
    {"type": "IGST","taxPerc": "0.00","taxAmount": "0.00"}]
    },"tcsInfo": {"tcsPerc": "0","tcsAmount": "0"},
    "discount": [{"type": "percentage","title": "tcs","value": "0",
    "amount": "0","description": "TCS discount"}
    ],"invoiceDate": "26-02-2021 20:28:53"
    }
 *
 * **/
class GetInvoice {
  static const String path = 'api/invoice';
  static const String fldTranId = 'tranid';

  static const resInvoiceNumber = 'invoiceNumber';
  static const resTransactionId = 'transactionId';
  static const resHsnCode = 'hsnCode';
  static const resRate = 'rate';
  static const resQuantity = 'quantity';
  static const resDate = 'invoiceDate';
  static const resSubtotal = 'grossAmount';
  static const resAmount = 'netAmount';
  static const resTaxes = 'totalTaxAmount';

  static const PDF_KEY_TRANID = 'TRANID';
  static const PDF_KEY_INVOICENUMBER = 'INVNUMBER';
  static const PDF_KEY_RATE = 'RATE';
  static const PDF_KEY_HSN = 'HSN';
  static const PDF_KEY_QUANTITY = 'QUANTITY';
  static const PDF_KEY_INVOICEDATE = 'INVDATE';
  static const PDF_KEY_CGST = 'CGST';
  static const PDF_KEY_SGST = 'SGST';
  static const PDF_KEY_IGST = 'IGST';
  static const PDF_KEY_CGST_AMOUNT = 'CGSTAMT';
  static const PDF_KEY_SGST_AMOUNT = 'SGSTAMT';
  static const PDF_KEY_IGST_AMOUNT = 'IGSTAMT';
  static const PDF_KEY_PRETAX_SUBTOTAL = 'PRETAX';
  static const PDF_KEY_AMOUNT = 'AMT';
}

class GetRateChart {
  static const String path = 'api/v1/rates/history';

  static const String fldFromTime = 'from';
  static const String fldToTime = 'to';

  static const String resRate = 'rRate';
  static const String resTimestamp = 'rTimestamp';
  static const String resType = 'rType';
}
