class CreateUser {
  static final String path = 'api/createUser';
  static final String fldMobile = 'mobile';
  static final String fldID = 'uid';
  static final String fldUserName = 'uname';
  static final String fldStateId = 'stateid';

  static final String resStatusCode = 'statusCode';
}

class GetRates {
  static final String path = 'api/rates';

  static final String resRates = 'rates';
  static final String resGoldBuyRate = 'gBuy';
  static final String resSilverBuyRate = 'sBuy';
  static final String resGoldSellRate = 'gSell';
  static final String resSilverSellRate = 'sSell';
  static final String resBlockId = 'blockId';
}

/**
 * {"quantity":"0.1051","totalAmount":"500.00","preTaxAmount":"485.44",
 * "metalType":"gold","rate":"4614.80","uniqueId":"fello_AMVPL5308BX",
 * "transactionId":"FL524816147746361350085490","userName":"shouryaditya.ray.lala",
 * "merchantTransactionId":"abcd-1342234-zxsweesa","mobileNumber":"9986643444",
 * "goldBalance":"0.4204","silverBalance":"0.0000","taxes":{"totalTaxAmount":"14.56",
 * "taxSplit":[{"type":"CGST","taxPerc":"1.50","taxAmount":"7.28"},{"type":"SGST",
 * "taxPerc":"1.50","taxAmount":"7.28"}]},"invoiceNumber":"GFL032104"}
 *
 * {"quantity":"0.0231","totalAmount":"109.00","preTaxAmount":"105.83",
 * "metalType":"gold","rate":"4577.90","uniqueId":"fello77AMVPL5308B",
 * "transactionId":"FL135416161312646250086020","userName":"felloGYyzamGPhSnadOXVpElZzuwoYWm",
 * "merchantTransactionId":"bQirAX5QnaZ2adQKYq9svY","mobileNumber":"9986643444",
 * "goldBalance":"0.0684","silverBalance":"0.0000","taxes":{"totalTaxAmount":"3.17",
 * "taxSplit":[{"type":"CGST","taxPerc":"1.50","taxAmount":"1.59"},
 * {"type":"SGST","taxPerc":"1.50","taxAmount":"1.59"}]},"invoiceNumber":"GFL032127"}
 * */
class SubmitGoldPurchase {
  static final String path = 'api/submitGoldPurchase';
  static final String fldLockPrice = 'lockprice';
  static final String fldAmount = 'amount';
  static final String fldMobile = 'mobile';
  static final String fldUid = 'uid';
  static final String fldPaymode = 'paymode';
  static final String fldUsername = 'uname';
  static final String fldStateId = 'stateid';
  static final String fldBlockId = 'blockid';
  static final String fldMerchantTranId = 'merchantTranId';

  static final String resTranId =
      'merchantTransactionId'; //generated by our server
  static final String resGoldBalance = 'goldBalance';
  static final String resPreTaxAmount = 'preTaxAmount';
  static final String resAugTranId = 'transactionId'; //generated by augmont
}

/**
 * {"merchantId":11055,"quantity":"0.0157","totalAmount":"70.00",
 * "preTaxAmount":"70.00","metalType":"gold","rate":"4441.50",
 * "uniqueId":"fello_AMVPL5308B","transactionId":"FL535216147821702650085173",
 * "userName":"shouryaditya.ray.lala","merchantTransactionId":"defg-2323dazxpst",
 * "mobileNumber":"9986643444","goldBalance":"0.0869","silverBalance":"0.0000",
 * "bankInfo":{"accountName":"INDUSIND BANK","accountNumber":"159986643444",
 * "ifscCode":"INDB0001394"}}
 * */
class SubmitGoldSell {
  static final String path = 'api/submitGoldQntSell';
  static final String fldLockPrice = 'lockprice';
  static final String fldAmount = 'amount';
  static final String fldQuantity = 'quantity';
  static final String fldMobile = 'mobile';
  static final String fldAugmontUid = 'uid';
  static final String fldUsername = 'uname';
  static final String fldAccHolderName = 'acctname';
  static final String fldAccNo = 'accno';
  static final String fldIfsc = 'ifsc';
  static final String fldBlockId = 'blockid';
  static final String fldMerchantTranId = 'merchantTranId';

  static final String resTranId = 'merchantTransactionId';
  static final String resGoldBalance = 'goldBalance';
  static final String resPreTaxAmount = 'preTaxAmount';
  static final String resAugTranId = 'transactionId';
}

class Passbook {
  static final String path = 'api/passbook';
  static final String fldAugmontUid = 'uid';

  static final String resGoldGrams = 'goldGrms';
  static final String resSilverGrams = 'silverGrms';
}

/**
 * {
    "invoiceNumber": "GFL022102",
    "userInfo": {"name": "shouryaditya.ray.lala","address": null,"city": null,
    "state": "Manipur","pincode": null,"email": null,"mobileNumber": "9986643444",
    "uniqueId": "fello_AMVPL5308B"},
    "transactionId": "FL763316143515330650085173","quantity": "0.1026",
    "metalType": "gold","hsnCode": "71141110","rate": "4727.40","unitType": "Gram",
    "grossAmount": "485.44","netAmount": "500.00",
    "taxes": {"totalTaxAmount": "14.56",
    "taxSplit": [{"type": "CGST","taxPerc": "1.50","taxAmount": "7.28"},
    {"type": "SGST","taxPerc": "1.50","taxAmount": "7.28"},
    {"type": "IGST","taxPerc": "0.00","taxAmount": "0.00"}]
    },"tcsInfo": {"tcsPerc": "0","tcsAmount": "0"},
    "discount": [{"type": "percentage","title": "tcs","value": "0",
    "amount": "0","description": "TCS discount"}
    ],"invoiceDate": "26-02-2021 20:28:53"
    }
 *
 * **/
class GetInvoice {
  static final String path = 'api/invoice';
  static final String fldTranId = 'tranid';

  static final resInvoiceNumber = 'invoiceNumber';
  static final resTransactionId = 'transactionId';
  static final resHsnCode = 'hsnCode';
  static final resRate = 'rate';
  static final resQuantity = 'quantity';
  static final resDate = 'invoiceDate';
  static final resSubtotal = 'grossAmount';
  static final resAmount = 'netAmount';
  static final resTaxes = 'totalTaxAmount';

  static const PDF_KEY_TRANID = 'TRANID';
  static const PDF_KEY_INVOICENUMBER = 'INVNUMBER';
  static const PDF_KEY_RATE = 'RATE';
  static const PDF_KEY_HSN = 'HSN';
  static const PDF_KEY_QUANTITY = 'QUANTITY';
  static const PDF_KEY_INVOICEDATE = 'INVDATE';
  static const PDF_KEY_CGST = 'CGST';
  static const PDF_KEY_SGST = 'SGST';
  static const PDF_KEY_IGST = 'IGST';
  static const PDF_KEY_CGST_AMOUNT = 'CGSTAMT';
  static const PDF_KEY_SGST_AMOUNT = 'SGSTAMT';
  static const PDF_KEY_IGST_AMOUNT = 'IGSTAMT';
  static const PDF_KEY_PRETAX_SUBTOTAL = 'PRETAX';
  static const PDF_KEY_AMOUNT = 'AMT';
}

class GetRateChart {
  static final String path = 'api/v1/rates/history';

  static final String fldFromTime = 'from';
  static final String fldToTime = 'to';

  static final String resRate = 'rRate';
  static final String resTimestamp = 'rTimestamp';
  static final String resType = 'rType';
}
