enum FailType {
  UserLoginOtpFailed,
  UserKYCFlagFetchFailed,
  UserICICAppCreationFailed,
  UserICICIBasicFieldUpdateFailed,
  UserICICIFatcaFieldUpdateFailed,
  UserICICIIncomeFieldUpdateFailed,
  UserInsufficientBankDetailFailed,
  UserICICIBankFieldUpdateFailed,
  UserIFSCNotFound,
  UserICICIOTPSendFailed,
  UserICICIOTPResendFailed,
  UserICICIPfCreationFailed,
  UserPfCreatedButFolioFailed,
  UserTransactionInitiateFailed,
  UserTransactionDetailSaveFailed,
  UserTransactionVerifyTimeoutFailed,
  UserICICIDepositUpdateDiscrepancy,
  UserICICIWthdrwUpdateDiscrepancy,
  UserWithdrawalCheckIMPSFailed,
  UserWithdrawalGetRedeemFailed,
  UserWithdrawalExitLoadFailed,
  UserWithdrawalSubmitFailed,
  UserRedemptionOTPSendFailed,
  UserAugmontPurchaseFailed,
  UserPaymentCompleteTxnFailed,
  UserAugmontSellFailed,
  UserRazorpayPurchaseFailed,
  UserAugmontDepositUpdateDiscrepancy,
  UserAugmontWthdrwUpdateDiscrepancy,
  UserAugmontRegnFailed,
  DailyPickParseFailed,
  FreshchatFail,
  RemoteConfigFailed,
  UserAugmontBalanceUpdateFailed,
  TambolaDrawNotificationSettingFailed,
  TambolaTicketGenerationFailed,
  RequestCallbackFailed,
  FelloRewardCardShareFailed,
  FelloRewardTextShareFailed,
  GameVoteFailed,
  ProfilePictureUpdateFailed,
  GoldRateFetchFailed,
  AndroidInAppUpdateFailed
}

extension ParseToString on FailType {
  String value() {
    return this.toString().split('.').last;
  }
}
