// import 'package:felloapp/core/model/golden_ticket_model.dart';
// import 'package:felloapp/core/model/journey_models/avatar_path_model.dart';
// import 'package:felloapp/core/model/journey_models/journey_asset_model.dart';
// import 'package:felloapp/core/model/journey_models/journey_page_model.dart';
// import 'package:felloapp/core/model/journey_models/journey_path_model.dart';
// import 'package:felloapp/core/model/journey_models/milestone_description.dart';
// import 'package:felloapp/core/model/journey_models/milestone_model.dart';

// const String path1 = "assets/journey/p1.svg";
// const String path2 = "assets/journey/p2.svg";
// const String path3 = "assets/journey/p3.svg";
// const String path4 = "assets/journey/p4.svg";
// const String path5 = "assets/journey/p5.svg";
// const String path6 = "assets/journey/p6.svg";
// const String path7 = "assets/journey/p7.svg";
// const String path8 = "assets/journey/p8.svg";

// const String base1 = "assets/journey/b1.svg";
// const String base2 = "assets/journey/b2.svg";
// const String base3 = "assets/journey/b3.svg";
// const String base4 = "assets/journey/b4.svg";
// const String base5 = "assets/journey/b5.svg";
// const String base6 = "assets/journey/b6.svg";
// const String base7 = "assets/journey/b7.svg";
// const String base8 = "assets/journey/b8.svg";

// const String ml1 = "assets/journey/ml1.svg";
// const String ml2 = "assets/journey/ml2.svg";
// const String ml3 = "assets/journey/ml3.svg";
// const String ml4 = "assets/journey/ml4.svg";
// const String ml5 = "assets/journey/ml5.svg";
// const String ml6 = "assets/journey/ml6.svg";
// const String ml7 = "assets/journey/ml7.svg";

// const String mls2 = "assets/journey/mls2.svg";
// const String mls4 = "assets/journey/mls4.svg";
// const String mls5 = "assets/journey/mls5.svg";
// const String mls6 = "assets/journey/mls6.svg";
// const String mls7 = "assets/journey/mls7.svg";

// //counting milestones from 1

// List<JourneyPage> get jourenyPages => [
//       JourneyPage(
//         bgAsset: JourneyAssetModel(
//             uri: "assets/journey/bg.svg",
//             height: 1,
//             width: 1,
//             name: 'bg',
//             page: 2,
//             assetType: "SVG"),
//         page: 1,
//         paths: [
//           JourneyPathModel(
//             id: 'b1',
//             asset: JourneyAssetModel(
//               uri: base1,
//               width: 0.2873,
//               height: 0.0985,
//               name: "b1",
//               page: 1,
//             ),
//             x: 0.3305,
//             y: 0.0991,
//             page: 1,
//             z: 2,
//             mlIndex: 1,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p1',
//             asset: JourneyAssetModel(
//               uri: path1,
//               width: 0.5262,
//               height: 0.1549,
//               name: "p1",
//               page: 1,
//             ),
//             x: 0.0613,
//             y: 0.1584,
//             page: 1,
//             z: 1,
//             mlIndex: 2,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p2',
//             asset: JourneyAssetModel(
//               uri: path2,
//               width: 0.2674,
//               height: 0.0991,
//               name: "p2",
//               page: 1,
//             ),
//             x: 0.0705,
//             y: 0.2813,
//             page: 1,
//             z: 0,
//             mlIndex: 2,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'b2',
//             asset: JourneyAssetModel(
//               uri: base2,
//               width: 0.435,
//               height: 0.1314,
//               name: "b2",
//               page: 1,
//             ),
//             x: 0.1991,
//             y: 0.3332,
//             page: 1,
//             z: 2,
//             mlIndex: 2,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p3',
//             asset: JourneyAssetModel(
//               uri: path3,
//               width: 0.4905,
//               height: 0.1429,
//               name: "p3",
//               page: 1,
//             ),
//             x: 0.3653,
//             y: 0.421,
//             page: 1,
//             z: 1,
//             mlIndex: 3,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'b3',
//             asset: JourneyAssetModel(
//               uri: base3,
//               width: 0.2948,
//               height: 0.0894,
//               name: "b3",
//               page: 1,
//             ),
//             x: 0.6106,
//             y: 0.5247,
//             page: 1,
//             z: 2,
//             mlIndex: 3,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p4',
//             asset: JourneyAssetModel(
//               uri: path4,
//               width: 0.3674,
//               height: 0.1151,
//               name: "p4",
//               page: 1,
//             ),
//             x: 0.356,
//             y: 0.5794,
//             page: 1,
//             z: 1,
//             mlIndex: 4,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'b4',
//             asset: JourneyAssetModel(
//               uri: base4,
//               width: 0.2598,
//               height: 0.0847,
//               name: "b4",
//               page: 1,
//             ),
//             x: 0.2053,
//             y: 0.6548,
//             page: 1,
//             z: 0,
//             mlIndex: 4,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p5',
//             asset: JourneyAssetModel(
//               uri: path5,
//               width: 0.0696,
//               height: 0.1046,
//               name: "p5",
//               page: 1,
//             ),
//             x: 0.2213,
//             y: 0.7167,
//             page: 1,
//             z: 0,
//             mlIndex: 5,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'b5',
//             asset: JourneyAssetModel(
//               uri: base5,
//               width: 0.3378,
//               height: 0.0992,
//               name: "b5",
//               page: 1,
//             ),
//             x: 0.008,
//             y: 0.7973,
//             page: 1,
//             z: 0,
//             mlIndex: 5,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p6',
//             asset: JourneyAssetModel(
//               uri: path6,
//               width: 0.4853,
//               height: 0.0677,
//               name: "p6",
//               page: 1,
//             ),
//             x: 0.216,
//             y: 0.8596,
//             page: 1,
//             z: 0,
//             mlIndex: 6,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'b6',
//             asset: JourneyAssetModel(
//               uri: base6,
//               width: 0.3386,
//               height: 0.1133,
//               name: "b6",
//               page: 1,
//             ),
//             x: 0.624,
//             y: 0.878,
//             page: 1,
//             z: 4,
//             mlIndex: 6,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p7',
//             asset: JourneyAssetModel(
//               uri: path7,
//               width: 0.2805,
//               height: 0.0822,
//               name: "p7",
//               page: 1,
//             ),
//             x: 0.464,
//             y: 0.9399,
//             page: 1,
//             z: 3,
//             mlIndex: 7,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'b7',
//             asset: JourneyAssetModel(
//               uri: base7,
//               width: 0.4506,
//               height: 0.1382,
//               name: "b7",
//               page: 1,
//             ),
//             x: 0.0906,
//             y: 0.9418,
//             page: 1,
//             z: 2,
//             mlIndex: 7,
//             isBase: true,
//           ),
//         ],
//         avatarPath: [
//           AvatarPathModel(
//               moveType: "linear", coords: [0.32, 0.8], page: 1, mlIndex: 1),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.24, 0.7], page: 1, mlIndex: 2),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.05, 0.66], page: 1, mlIndex: 2),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.33, 0.58], page: 1, mlIndex: 2),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.48, 0.55], page: 1, mlIndex: 3),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.7, 0.41], page: 1, mlIndex: 3),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.42, 0.32], page: 1, mlIndex: 4),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.26, 0.3], page: 1, mlIndex: 4),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.26, 0.17], page: 1, mlIndex: 5),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.12, 0.14], page: 1, mlIndex: 5),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.08, 0.1], page: 1, mlIndex: 6),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.65, 0.05], page: 1, mlIndex: 6),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.7, 0.03], page: 1, mlIndex: 7),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.58, 0.0], page: 1, mlIndex: 7),
//         ],
//         milestones: [
//           MilestoneModel(
//               id: 'm1',
//               asset: JourneyAssetModel(
//                 uri: ml1,
//                 name: 'm1',
//                 width: 0.1177,
//                 height: 0.0824,
//                 page: 1,
//               ),
//               x: 0.43,
//               y: 0.1528,
//               page: 1,
//               index: 1,
//               animType: "NONE",
//               steps: [
//                 MlSteps(
//                   title: "Watch Walkthrough and win 100 Tokens to get started!",
//                   subtitle: "Description of the milestone",
//                 )
//               ],
//               rewards: [
//                 Reward(value: 100, type: "FLC"),
//               ],
//               actionUri: "/walkthrough",
//               isCompleted: true),
//           MilestoneModel(
//             id: 'm2',
//             asset: JourneyAssetModel(
//               uri: ml2,
//               name: 'm2',
//               width: 0.1491,
//               height: 0.0816,
//               page: 1,
//             ),
//             x: 0.348,
//             y: 0.3966,
//             page: 1,
//             index: 2, //index
//             animType: "FLOAT",
//             steps: [
//               //steps
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/profile",
//             shadow: MilestoneShadowModel(
//               id: 'ms2',
//               name: 'ms2',
//               asset: JourneyAssetModel(
//                 uri: mls2,
//                 width: 0.1225,
//                 height: 0.0308,
//                 name: 'ms2',
//                 page: 1,
//               ),
//               x: 0.3616,
//               y: 0.3877,
//               index: 1,
//               page: 1,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm3',
//             asset: JourneyAssetModel(
//               uri: ml3,
//               name: 'm3',
//               width: 0.1158,
//               height: 0.094,
//               page: 1,
//             ),
//             x: 0.704,
//             y: 0.5673,
//             page: 1,
//             index: 3,
//             animType: "FLOAT",
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/profile",
//           ),
//           MilestoneModel(
//             id: 'm4',
//             asset: JourneyAssetModel(
//               uri: ml4,
//               name: 'm4',
//               width: 0.1107,
//               height: 0.0591,
//               page: 1,
//             ),
//             x: 0.2795,
//             y: 0.707,
//             page: 1,
//             index: 4,
//             animType: "ROTATE",
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'ms4',
//               name: 'ms4',
//               asset: JourneyAssetModel(
//                 uri: mls4,
//                 width: 0.0775,
//                 height: 0.0327,
//                 name: 'ms4',
//                 page: 1,
//               ),
//               x: 0.2692,
//               y: 0.6939,
//               index: 1,
//               page: 1,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm5',
//             asset: JourneyAssetModel(
//               uri: ml5,
//               name: 'm5',
//               width: 0.1573,
//               height: 0.0801,
//               page: 1,
//             ),
//             x: 0.0826,
//             y: 0.8397,
//             page: 1,
//             index: 5,
//             animType: "NONE",
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'ms5',
//               name: 'ms5',
//               asset: JourneyAssetModel(
//                 uri: mls5,
//                 width: 0.1513,
//                 height: 0.0403,
//                 page: 1,
//                 name: 'ms5',
//               ),
//               x: 0.08,
//               y: 0.8291,
//               index: 1,
//               page: 1,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm6',
//             asset: JourneyAssetModel(
//               uri: ml6,
//               name: 'm6',
//               width: 0.1449,
//               height: 0.1629,
//               page: 1,
//             ),
//             x: 0.712,
//             y: 0.9121,
//             page: 1,
//             index: 6,
//             animType: "FLOAT",
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'ms6',
//               name: 'ms6',
//               asset: JourneyAssetModel(
//                 uri: mls6,
//                 width: 0.0714,
//                 height: 0.0123,
//                 name: 'ms6',
//                 page: 1,
//               ),
//               x: 0.7475,
//               y: 0.9191,
//               index: 1,
//               page: 1,
//             ),
//           ),
//         ],
//       ),
//       JourneyPage(
//         bgAsset: JourneyAssetModel(
//             uri: "assets/journey/bg.svg",
//             height: 1,
//             width: 1,
//             name: 'bg',
//             page: 2,
//             assetType: "SVG"),
//         page: 2,
//         paths: [
//           JourneyPathModel(
//             id: 'p8',
//             asset: JourneyAssetModel(
//               uri: path8,
//               width: 0.2961,
//               height: 0.0947,
//               name: "p8",
//               page: 2,
//             ),
//             mlIndex: 8,
//             x: 0.3973,
//             y: 0.0419,
//             page: 2,
//             z: 1,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'b8',
//             asset: JourneyAssetModel(
//               uri: base3,
//               width: 0.2948,
//               height: 0.0894,
//               name: "b3",
//               page: 2,
//             ),
//             x: 0.56,
//             y: 0.0985,
//             page: 2,
//             z: 3,
//             mlIndex: 8,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p9',
//             asset: JourneyAssetModel(
//               uri: path3,
//               width: 0.4905,
//               height: 0.1429,
//               name: "p3",
//               page: 2,
//             ),
//             x: 0.304,
//             y: 0.1526,
//             page: 2,
//             mlIndex: 9,
//             z: 2,
//             isBase: false,
//             hFlip: true,
//           ),
//           JourneyPathModel(
//             id: 'b9',
//             asset: JourneyAssetModel(
//               uri: base4,
//               width: 0.2598,
//               height: 0.0847,
//               name: "b4",
//               page: 2,
//             ),
//             x: 0.2773,
//             y: 0.2512,
//             page: 2,
//             mlIndex: 9,
//             z: 1,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p10',
//             asset: JourneyAssetModel(
//               uri: path5,
//               width: 0.0696,
//               height: 0.1046,
//               name: "p5",
//               page: 2,
//             ),
//             x: 0.3053,
//             y: 0.3115,
//             page: 2,
//             mlIndex: 10,
//             z: 0,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'b10',
//             asset: JourneyAssetModel(
//               uri: base5,
//               width: 0.3378,
//               height: 0.0992,
//               name: "b5",
//               page: 2,
//             ),
//             x: 0.092,
//             y: 0.3921,
//             page: 2,
//             mlIndex: 10,
//             z: 2,
//             isBase: true,
//           ),
//           JourneyPathModel(
//               id: 'p11',
//               asset: JourneyAssetModel(
//                 uri: path4,
//                 width: 0.3674,
//                 height: 0.1151,
//                 name: "p4",
//                 page: 2,
//               ),
//               x: 0.2853,
//               y: 0.4525,
//               page: 2,
//               mlIndex: 11,
//               z: 1,
//               hFlip: true),
//           JourneyPathModel(
//               id: 'b11',
//               asset: JourneyAssetModel(
//                 uri: base7,
//                 width: 0.4506,
//                 height: 0.1382,
//                 name: "b7",
//                 page: 2,
//               ),
//               x: 0.4933,
//               y: 0.5021,
//               page: 2,
//               mlIndex: 11,
//               z: 2,
//               isBase: true,
//               hFlip: true),
//           JourneyPathModel(
//             id: 'p12',
//             asset: JourneyAssetModel(
//               uri: path1,
//               width: 0.5262,
//               height: 0.1549,
//               name: "p1",
//               page: 2,
//             ),
//             x: 0.2506,
//             y: 0.5901,
//             page: 2,
//             mlIndex: 12,
//             z: 1,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'p13',
//             asset: JourneyAssetModel(
//               name: 'p2',
//               uri: path2,
//               width: 0.2674,
//               height: 0.0991,
//               page: 2,
//             ),
//             x: 0.26,
//             y: 0.7142,
//             page: 2,
//             mlIndex: 12,
//             z: 0,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'b12',
//             asset: JourneyAssetModel(
//               name: 'b4',
//               uri: base4,
//               width: 0.2598,
//               height: 0.0847,
//               page: 2,
//             ),
//             x: 0.4213,
//             y: 0.7711,
//             page: 2,
//             mlIndex: 12,
//             z: 1,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p14',
//             asset: JourneyAssetModel(
//               name: 'p3',
//               uri: path3,
//               width: 0.4905,
//               height: 0.1429,
//               page: 2,
//             ),
//             x: 0.488,
//             y: 0.8241,
//             page: 2,
//             mlIndex: 13,
//             z: 0,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'b13',
//             asset: JourneyAssetModel(
//               name: 'b3',
//               uri: base3,
//               width: 0.2948,
//               height: 0.0894,
//               page: 2,
//             ),
//             x: 0.704,
//             y: 0.9204,
//             page: 2,
//             mlIndex: 13,
//             z: 1,
//             isBase: true,
//           ),
//           JourneyPathModel(
//             id: 'p15',
//             asset: JourneyAssetModel(
//               name: 'p6',
//               uri: path6,
//               width: 0.4853,
//               height: 0.0677,
//               page: 2,
//             ),
//             x: 0.2853,
//             y: 0.9655,
//             page: 2,
//             mlIndex: 14,
//             z: 0,
//             isBase: false,
//           ),
//           JourneyPathModel(
//             id: 'b14',
//             asset: JourneyAssetModel(
//               name: 'b6',
//               uri: base6,
//               width: 0.3386,
//               height: 0.1133,
//               page: 2,
//             ),
//             x: 0.0373,
//             y: 0.9913,
//             page: 2,
//             mlIndex: 14,
//             z: 4,
//             isBase: true,
//           ),
//         ],
//         avatarPath: [
//           AvatarPathModel(
//               moveType: "linear", coords: [0.26, 0.98], page: 2, mlIndex: 7),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.4, 0.9], page: 2, mlIndex: 8),
//           AvatarPathModel(
//               moveType: "linear", coords: [0.6, 0.84], page: 2, mlIndex: 8),
//         ],
//         milestones: [
//           MilestoneModel(
//             id: 'm7',
//             asset: JourneyAssetModel(
//               uri: ml7,
//               name: 'm7',
//               width: 0.213,
//               height: 0.0868,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.2106,
//             y: 0.0207,
//             page: 2,
//             index: 7,
//             animType: "NONE",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'ms7',
//               name: 'ms7',
//               asset: JourneyAssetModel(
//                 uri: mls7,
//                 name: 'ms7',
//                 width: 0.0714,
//                 height: 0.0179,
//                 page: 2,
//               ),
//               x: 0.336,
//               y: 0.0115,
//               index: 7,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm8',
//             asset: JourneyAssetModel(
//               uri: ml3,
//               name: 'm3',
//               width: 0.1158,
//               height: 0.094,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.6534,
//             y: 0.1325,
//             page: 2,
//             index: 8,
//             animType: "FLOAT",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/profile",
//           ),
//           MilestoneModel(
//             id: 'm9',
//             asset: JourneyAssetModel(
//               uri: ml4,
//               name: 'm4',
//               width: 0.1107,
//               height: 0.0591,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.3515,
//             y: 0.3028,
//             page: 2,
//             index: 9,
//             animType: "ROTATE",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'ms9',
//               name: 'ms4',
//               asset: JourneyAssetModel(
//                 uri: mls4,
//                 name: 'ms4',
//                 width: 0.0775,
//                 height: 0.0327,
//                 page: 2,
//               ),
//               x: 0.3412,
//               y: 0.2897,
//               index: 9,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm10',
//             asset: JourneyAssetModel(
//               uri: ml5,
//               name: 'm5',
//               width: 0.1573,
//               height: 0.0801,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.1667,
//             y: 0.4346,
//             page: 2,
//             index: 10,
//             animType: "NONE",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'm10',
//               name: 'ms5',
//               asset: JourneyAssetModel(
//                 uri: mls5,
//                 name: 'ms5',
//                 width: 0.1513,
//                 height: 0.0403,
//                 page: 2,
//               ),
//               x: 0.164,
//               y: 0.4239,
//               index: 10,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm11',
//             asset: JourneyAssetModel(
//               uri: ml7,
//               name: 'm7',
//               width: 0.213,
//               height: 0.0868,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.5786,
//             y: 0.581,
//             page: 2,
//             index: 11,
//             hFlip: true,
//             animType: "NONE",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//                 id: 'ms11',
//                 name: 'ms7',
//                 asset: JourneyAssetModel(
//                   uri: mls7,
//                   name: 'ms7',
//                   width: 0.0714,
//                   height: 0.0179,
//                   page: 2,
//                 ),
//                 x: 0.6272,
//                 y: 0.5719,
//                 index: 11,
//                 page: 2,
//                 hFlip: true),
//           ),
//           MilestoneModel(
//             id: 'm12',
//             asset: JourneyAssetModel(
//               uri: ml4,
//               name: 'm14',
//               width: 0.1107,
//               height: 0.0591,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.4929,
//             y: 0.8213,
//             page: 2,
//             index: 12,
//             animType: "ROTATE",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/task",
//             shadow: MilestoneShadowModel(
//               id: 'ms12',
//               name: 'ms4',
//               asset: JourneyAssetModel(
//                 uri: mls4,
//                 name: 'm1s4',
//                 width: 0.0775,
//                 height: 0.0327,
//                 page: 2,
//               ),
//               x: 0.4826,
//               y: 0.8082,
//               index: 12,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             id: 'm13',
//             asset: JourneyAssetModel(
//               uri: ml2,
//               name: 'm2',
//               width: 0.1491,
//               height: 0.0816,
//               page: 2,
//             ),
//             steps: [
//               MlSteps(
//                 title: "Watch Walkthrough and win 100 Tokens to get started!",
//                 subtitle: "Description of the milestone",
//               )
//             ],
//             x: 0.776,
//             y: 0.9627,
//             page: 2,
//             index: 13,
//             animType: "FLOAT",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             actionUri: "/profile",
//             shadow: MilestoneShadowModel(
//               id: 'ms13',
//               name: 'ms2',
//               asset: JourneyAssetModel(
//                 uri: mls2,
//                 name: 'ms2',
//                 width: 0.1225,
//                 height: 0.0308,
//                 page: 2,
//               ),
//               x: 0.7895,
//               y: 0.9539,
//               index: 13,
//               page: 2,
//             ),
//           ),
//         ],
//       ),
//       // JourneyPage(
//       //     bgImage: "assets/journey/bg.svg",
//       //     paths: [
//       //       JourneyPathModel(
//       //         asset: path3,
//       //         x: 0.1013,
//       //         y: 0.0405,
//       //         page: 3,
//       //         width: 0.4905,
//       //         height: 0.1429,
//       //         z: 1,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base1,
//       //         x: 0.3305,
//       //         y: 0.0991,
//       //         page: 3,
//       //         width: 0.2873,
//       //         height: 0.0985,
//       //         z: 2,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: "SVG",
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path1,
//       //         x: 0.0613,
//       //         y: 0.1584,
//       //         page: 3,
//       //         width: 0.5262,
//       //         height: 0.1549,
//       //         z: 1,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path2,
//       //         x: 0.0705,
//       //         y: 0.2813,
//       //         page: 3,
//       //         width: 0.2674,
//       //         height: 0.0991,
//       //         z: 0,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base2,
//       //         x: 0.1991,
//       //         y: 0.3332,
//       //         page: 3,
//       //         width: 0.435,
//       //         height: 0.1314,
//       //         z: 2,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path3,
//       //         x: 0.3653,
//       //         y: 0.421,
//       //         page: 3,
//       //         width: 0.4905,
//       //         height: 0.1429,
//       //         z: 1,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base3,
//       //         x: 0.6106,
//       //         y: 0.5247,
//       //         page: 3,
//       //         width: 0.2948,
//       //         height: 0.0894,
//       //         z: 2,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path4,
//       //         x: 0.356,
//       //         y: 0.5794,
//       //         page: 3,
//       //         width: 0.3674,
//       //         height: 0.1151,
//       //         z: 1,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base4,
//       //         x: 0.2053,
//       //         y: 0.6548,
//       //         page: 3,
//       //         width: 0.2598,
//       //         height: 0.0847,
//       //         z: 0,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path5,
//       //         x: 0.2213,
//       //         y: 0.7167,
//       //         page: 3,
//       //         width: 0.0696,
//       //         height: 0.1046,
//       //         z: 0,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base5,
//       //         x: 0.008,
//       //         y: 0.7973,
//       //         page: 3,
//       //         width: 0.3378,
//       //         height: 0.0992,
//       //         z: 0,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path6,
//       //         x: 0.216,
//       //         y: 0.8596,
//       //         page: 3,
//       //         width: 0.4853,
//       //         height: 0.0677,
//       //         z: 0,
//       //         level: 1,
//       //         isBase: false,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base6,
//       //         x: 0.624,
//       //         y: 0.878,
//       //         page: 3,
//       //         width: 0.3386,
//       //         height: 0.1133,
//       //         z: 4,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: path7,
//       //         x: 0.464,
//       //         y: 0.9399,
//       //         page: 3,
//       //         width: 0.2805,
//       //         height: 0.0822,
//       //         z: 3,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //       JourneyPathModel(
//       //         asset: base7,
//       //         x: 0.0906,
//       //         y: 0.9418,
//       //         page: 3,
//       //         width: 0.4506,
//       //         height: 0.1382,
//       //         z: 2,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //       ),
//       //     ],
//       //     page: 3,
//       //     level: 1,
//       //     avatarPath: [],
//       //     milestones: [
//       //       MilestoneModel(
//       //         asset: ml6,
//       //         width: 0.1449,
//       //         height: 0.1629,
//       //         x: 0.143,
//       //         y: 0.0247,
//       //         page: 3,
//       //         level: 1,
//       //         animType: "FLOAT",
//       //         assetType: "SVG",
//       //         description: "Do some task",
//       //         rewards: [
//       //           Reward(value: 200, type: "FLC"),
//       //           Reward(value: 50, type: "Money"),
//       //         ],
//       //         actionUri: "/task",
//       //         shadow: MilestoneShadowModel(
//       //           asset: mls6,
//       //           width: 0.0714,
//       //           height: 0.0123,
//       //           x: 0.1762,
//       //           y: 0.0324,
//       //           level: 1,
//       //           page: 3,
//       //         ),
//       //       ),
//       //       MilestoneModel(
//       //           asset: ml1,
//       //           width: 0.1177,
//       //           height: 0.0824,
//       //           x: 0.43,
//       //           y: 0.1528,
//       //           page: 3,
//       //           level: 1,
//       //           animType: "NONE",
//       //           assetType: "SVG",
//       //           description:
//       //               "Watch Walkthrough and win 100 Tokens to get started!",
//       //           rewards: [
//       //             Reward(value: 100, type: "FLC"),
//       //           ],
//       //           actionUri: "/walkthrough",
//       //           isCompleted: true),
//       //       MilestoneModel(
//       //         asset: ml2,
//       //         width: 0.1491,
//       //         height: 0.0816,
//       //         x: 0.348,
//       //         y: 0.3966,
//       //         page: 3,
//       //         level: 1,
//       //         animType: "FLOAT",
//       //         assetType: "SVG",
//       //         description: "Complete your profile and get 200 Tokens and ₹50",
//       //         rewards: [
//       //           Reward(value: 200, type: "FLC"),
//       //           Reward(value: 50, type: "Money"),
//       //         ],
//       //         actionUri: "/profile",
//       //         shadow: MilestoneShadowModel(
//       //           asset: mls2,
//       //           width: 0.1225,
//       //           height: 0.0308,
//       //           x: 0.3616,
//       //           y: 0.3877,
//       //           level: 1,
//       //           page: 3,
//       //         ),
//       //       ),
//       //       MilestoneModel(
//       //         asset: ml3,
//       //         width: 0.1158,
//       //         height: 0.094,
//       //         x: 0.704,
//       //         y: 0.5673,
//       //         page: 3,
//       //         level: 1,
//       //         animType: "FLOAT",
//       //         assetType: "SVG",
//       //         description: "Do some task",
//       //         rewards: [
//       //           Reward(value: 200, type: "FLC"),
//       //           Reward(value: 50, type: "Money"),
//       //         ],
//       //         actionUri: "/profile",
//       //       ),
//       //       MilestoneModel(
//       //         asset: ml4,
//       //         width: 0.1107,
//       //         height: 0.0591,
//       //         x: 0.2795,
//       //         y: 0.707,
//       //         page: 3,
//       //         level: 1,
//       //         animType: "ROTATE",
//       //         assetType: "SVG",
//       //         description: "Do some task",
//       //         rewards: [
//       //           Reward(value: 200, type: "FLC"),
//       //           Reward(value: 50, type: "Money"),
//       //         ],
//       //         actionUri: "/task",
//       //         shadow: MilestoneShadowModel(
//       //           asset: mls4,
//       //           width: 0.0775,
//       //           height: 0.0327,
//       //           x: 0.2692,
//       //           y: 0.6939,
//       //           level: 1,
//       //           page: 3,
//       //         ),
//       //       ),
//       //       MilestoneModel(
//       //         asset: ml5,
//       //         width: 0.1573,
//       //         height: 0.0801,
//       //         x: 0.0826,
//       //         y: 0.8397,
//       //         page: 3,
//       //         level: 1,
//       //         animType: "NONE",
//       //         assetType: "SVG",
//       //         description: "Do some task",
//       //         rewards: [
//       //           Reward(value: 200, type: "FLC"),
//       //           Reward(value: 50, type: "Money"),
//       //         ],
//       //         actionUri: "/task",
//       //         shadow: MilestoneShadowModel(
//       //           asset: mls5,
//       //           width: 0.1513,
//       //           height: 0.0403,
//       //           x: 0.08,
//       //           y: 0.8291,
//       //           level: 1,
//       //           page: 3,
//       //         ),
//       //       ),
//       //       MilestoneModel(
//       //         asset: ml6,
//       //         width: 0.1449,
//       //         height: 0.1629,
//       //         x: 0.712,
//       //         y: 0.9121,
//       //         page: 3,
//       //         level: 1,
//       //         animType: "FLOAT",
//       //         assetType: "SVG",
//       //         description: "Do some task",
//       //         rewards: [
//       //           Reward(value: 200, type: "FLC"),
//       //           Reward(value: 50, type: "Money"),
//       //         ],
//       //         actionUri: "/task",
//       //         shadow: MilestoneShadowModel(
//       //           asset: mls6,
//       //           width: 0.0714,
//       //           height: 0.0123,
//       //           x: 0.7475,
//       //           y: 0.9191,
//       //           level: 1,
//       //           page: 3,
//       //         ),
//       //       ),
//       //     ]),
//       // JourneyPage(
//       //   bgImage: "assets/journey/bg.svg",
//       //   paths: [
//       //     JourneyPathModel(
//       //       asset: path8,
//       //       x: 0.3973,
//       //       y: 0.0419,
//       //       page: 4,
//       //       width: 0.2961,
//       //       height: 0.0947,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base3,
//       //       x: 0.56,
//       //       y: 0.0985,
//       //       page: 4,
//       //       width: 0.2948,
//       //       height: 0.0894,
//       //       z: 3,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path3,
//       //       x: 0.304,
//       //       y: 0.1526,
//       //       page: 4,
//       //       width: 0.4905,
//       //       height: 0.1429,
//       //       z: 2,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //       hFlip: true,
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base4,
//       //       x: 0.2773,
//       //       y: 0.2512,
//       //       page: 4,
//       //       width: 0.2598,
//       //       height: 0.0847,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path5,
//       //       x: 0.3053,
//       //       y: 0.3115,
//       //       page: 4,
//       //       width: 0.0696,
//       //       height: 0.1046,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base5,
//       //       x: 0.092,
//       //       y: 0.3921,
//       //       page: 4,
//       //       width: 0.3378,
//       //       height: 0.0992,
//       //       z: 2,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //         asset: path4,
//       //         x: 0.2853,
//       //         y: 0.4525,
//       //         page: 4,
//       //         width: 0.3674,
//       //         height: 0.1151,
//       //         z: 1,
//       //         level: 1,
//       //         isBase: false,
//       //         source: "AST",
//       //         type: 'SVG',
//       //         hFlip: true),
//       //     JourneyPathModel(
//       //         asset: base7,
//       //         x: 0.4933,
//       //         y: 0.5021,
//       //         page: 4,
//       //         width: 0.4506,
//       //         height: 0.1382,
//       //         z: 2,
//       //         level: 1,
//       //         isBase: true,
//       //         source: "AST",
//       //         type: 'SVG',
//       //         hFlip: true),
//       //     JourneyPathModel(
//       //       asset: path1,
//       //       x: 0.2506,
//       //       y: 0.5901,
//       //       page: 4,
//       //       width: 0.5262,
//       //       height: 0.1549,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path2,
//       //       x: 0.26,
//       //       y: 0.7142,
//       //       page: 4,
//       //       width: 0.2674,
//       //       height: 0.0991,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base4,
//       //       x: 0.4213,
//       //       y: 0.7711,
//       //       page: 4,
//       //       width: 0.2598,
//       //       height: 0.0847,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path3,
//       //       x: 0.488,
//       //       y: 0.8241,
//       //       page: 4,
//       //       width: 0.4905,
//       //       height: 0.1429,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base3,
//       //       x: 0.704,
//       //       y: 0.9204,
//       //       page: 4,
//       //       width: 0.2948,
//       //       height: 0.0894,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path6,
//       //       x: 0.2853,
//       //       y: 0.9655,
//       //       page: 4,
//       //       width: 0.4853,
//       //       height: 0.0677,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: false,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base6,
//       //       x: 0.0373,
//       //       y: 0.9913,
//       //       page: 4,
//       //       width: 0.3386,
//       //       height: 0.1133,
//       //       z: 4,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //   ],
//       //   page: 4,
//       //   level: 1,
//       //   avatarPath: [],
//       //   milestones: [
//       //     MilestoneModel(
//       //       asset: ml7,
//       //       width: 0.213,
//       //       height: 0.0868,
//       //       x: 0.2106,
//       //       y: 0.0207,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "NONE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls7,
//       //         width: 0.0714,
//       //         height: 0.0179,
//       //         x: 0.336,
//       //         y: 0.0115,
//       //         level: 1,
//       //         page: 4,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml3,
//       //       width: 0.1158,
//       //       height: 0.094,
//       //       x: 0.6534,
//       //       y: 0.1325,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "FLOAT",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/profile",
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml4,
//       //       width: 0.1107,
//       //       height: 0.0591,
//       //       x: 0.3515,
//       //       y: 0.3028,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "ROTATE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls4,
//       //         width: 0.0775,
//       //         height: 0.0327,
//       //         x: 0.3412,
//       //         y: 0.2897,
//       //         level: 1,
//       //         page: 4,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml5,
//       //       width: 0.1573,
//       //       height: 0.0801,
//       //       x: 0.1667,
//       //       y: 0.4346,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "NONE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls5,
//       //         width: 0.1513,
//       //         height: 0.0403,
//       //         x: 0.164,
//       //         y: 0.4239,
//       //         level: 1,
//       //         page: 4,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml7,
//       //       width: 0.213,
//       //       height: 0.0868,
//       //       x: 0.5786,
//       //       y: 0.581,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "NONE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       hFlip: true,
//       //       shadow: MilestoneShadowModel(
//       //           asset: mls7,
//       //           width: 0.0714,
//       //           height: 0.0179,
//       //           x: 0.6272,
//       //           y: 0.5719,
//       //           level: 1,
//       //           page: 4,
//       //           hFlip: true),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml4,
//       //       width: 0.1107,
//       //       height: 0.0591,
//       //       x: 0.4929,
//       //       y: 0.8213,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "ROTATE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls4,
//       //         width: 0.0775,
//       //         height: 0.0327,
//       //         x: 0.4826,
//       //         y: 0.8082,
//       //         level: 1,
//       //         page: 4,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml2,
//       //       width: 0.1491,
//       //       height: 0.0816,
//       //       x: 0.776,
//       //       y: 0.9627,
//       //       page: 4,
//       //       level: 1,
//       //       animType: "FLOAT",
//       //       assetType: "SVG",
//       //       description: "Complete your profile and get 200 Tokens and ₹50",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/profile",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls2,
//       //         width: 0.1225,
//       //         height: 0.0308,
//       //         x: 0.7895,
//       //         y: 0.9539,
//       //         level: 1,
//       //         page: 4,
//       //       ),
//       //     ),
//       //   ],
//       // ),
//       // JourneyPage(
//       //   bgImage: "assets/journey/bg.svg",
//       //   paths: [
//       //     JourneyPathModel(
//       //       asset: path3,
//       //       x: 0.1013,
//       //       y: 0.0405,
//       //       page: 5,
//       //       width: 0.4905,
//       //       height: 0.1429,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base1,
//       //       x: 0.3305,
//       //       y: 0.0991,
//       //       page: 5,
//       //       width: 0.2873,
//       //       height: 0.0985,
//       //       z: 2,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: "SVG",
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path1,
//       //       x: 0.0613,
//       //       y: 0.1584,
//       //       page: 5,
//       //       width: 0.5262,
//       //       height: 0.1549,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path2,
//       //       x: 0.0705,
//       //       y: 0.2813,
//       //       page: 5,
//       //       width: 0.2674,
//       //       height: 0.0991,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base2,
//       //       x: 0.1991,
//       //       y: 0.3332,
//       //       page: 5,
//       //       width: 0.435,
//       //       height: 0.1314,
//       //       z: 2,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path3,
//       //       x: 0.3653,
//       //       y: 0.421,
//       //       page: 5,
//       //       width: 0.4905,
//       //       height: 0.1429,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base3,
//       //       x: 0.6106,
//       //       y: 0.5247,
//       //       page: 5,
//       //       width: 0.2948,
//       //       height: 0.0894,
//       //       z: 2,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path4,
//       //       x: 0.356,
//       //       y: 0.5794,
//       //       page: 5,
//       //       width: 0.3674,
//       //       height: 0.1151,
//       //       z: 1,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base4,
//       //       x: 0.2053,
//       //       y: 0.6548,
//       //       page: 5,
//       //       width: 0.2598,
//       //       height: 0.0847,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: path5,
//       //       x: 0.2213,
//       //       y: 0.7167,
//       //       page: 5,
//       //       width: 0.0696,
//       //       height: 0.1046,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //     JourneyPathModel(
//       //       asset: base5,
//       //       x: 0.008,
//       //       y: 0.7973,
//       //       page: 5,
//       //       width: 0.3378,
//       //       height: 0.0992,
//       //       z: 0,
//       //       level: 1,
//       //       isBase: true,
//       //       source: "AST",
//       //       type: 'SVG',
//       //     ),
//       //   ],
//       //   page: 5,
//       //   level: 2,
//       //   avatarPath: [],
//       //   milestones: [
//       //     MilestoneModel(
//       //       asset: ml6,
//       //       width: 0.1449,
//       //       height: 0.1629,
//       //       x: 0.143,
//       //       y: 0.0247,
//       //       page: 5,
//       //       level: 1,
//       //       animType: "FLOAT",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls6,
//       //         width: 0.0714,
//       //         height: 0.0123,
//       //         x: 0.1762,
//       //         y: 0.0324,
//       //         level: 1,
//       //         page: 5,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //         asset: ml1,
//       //         width: 0.1177,
//       //         height: 0.0824,
//       //         x: 0.43,
//       //         y: 0.1528,
//       //         page: 5,
//       //         level: 1,
//       //         animType: "NONE",
//       //         assetType: "SVG",
//       //         description:
//       //             "Watch Walkthrough and win 100 Tokens to get started!",
//       //         rewards: [
//       //           Reward(value: 100, type: "FLC"),
//       //         ],
//       //         actionUri: "/walkthrough",
//       //         isCompleted: true),
//       //     MilestoneModel(
//       //       asset: ml2,
//       //       width: 0.1491,
//       //       height: 0.0816,
//       //       x: 0.348,
//       //       y: 0.3966,
//       //       page: 5,
//       //       level: 1,
//       //       animType: "FLOAT",
//       //       assetType: "SVG",
//       //       description: "Complete your profile and get 200 Tokens and ₹50",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/profile",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls2,
//       //         width: 0.1225,
//       //         height: 0.0308,
//       //         x: 0.3616,
//       //         y: 0.3877,
//       //         level: 1,
//       //         page: 5,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml3,
//       //       width: 0.1158,
//       //       height: 0.094,
//       //       x: 0.704,
//       //       y: 0.5673,
//       //       page: 5,
//       //       level: 1,
//       //       animType: "FLOAT",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/profile",
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml4,
//       //       width: 0.1107,
//       //       height: 0.0591,
//       //       x: 0.2795,
//       //       y: 0.707,
//       //       page: 5,
//       //       level: 1,
//       //       animType: "ROTATE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls4,
//       //         width: 0.0775,
//       //         height: 0.0327,
//       //         x: 0.2692,
//       //         y: 0.6939,
//       //         level: 1,
//       //         page: 5,
//       //       ),
//       //     ),
//       //     MilestoneModel(
//       //       asset: ml5,
//       //       width: 0.1573,
//       //       height: 0.0801,
//       //       x: 0.0826,
//       //       y: 0.8397,
//       //       page: 5,
//       //       level: 1,
//       //       animType: "NONE",
//       //       assetType: "SVG",
//       //       description: "Do some task",
//       //       rewards: [
//       //         Reward(value: 200, type: "FLC"),
//       //         Reward(value: 50, type: "Money"),
//       //       ],
//       //       actionUri: "/task",
//       //       shadow: MilestoneShadowModel(
//       //         asset: mls5,
//       //         width: 0.1513,
//       //         height: 0.0403,
//       //         x: 0.08,
//       //         y: 0.8291,
//       //         level: 1,
//       //         page: 5,
//       //       ),
//       //     ),
//       //   ],
//       // )
//     ];
