// import 'package:felloapp/core/model/golden_ticket_model.dart';
// import 'package:felloapp/core/model/journey_models/avatar_path_model.dart';
// import 'package:felloapp/core/model/journey_models/journey_page.dart';
// import 'package:felloapp/core/model/journey_models/journey_path_model.dart';
// import 'package:felloapp/core/model/journey_models/milestone_model.dart';

// const String path1 = "assets/journey/p1.svg";
// const String path2 = "assets/journey/p2.svg";
// const String path3 = "assets/journey/p3.svg";
// const String path4 = "assets/journey/p4.svg";
// const String path5 = "assets/journey/p5.svg";
// const String path6 = "assets/journey/p6.svg";
// const String path7 = "assets/journey/p7.svg";
// const String path8 = "assets/journey/p8.svg";

// const String base1 = "assets/journey/b1.svg";
// const String base2 = "assets/journey/b2.svg";
// const String base3 = "assets/journey/b3.svg";
// const String base4 = "assets/journey/b4.svg";
// const String base5 = "assets/journey/b5.svg";
// const String base6 = "assets/journey/b6.svg";
// const String base7 = "assets/journey/b7.svg";
// const String base8 = "assets/journey/b8.svg";

// const String ml1 = "assets/journey/ml1.svg";
// const String ml2 = "assets/journey/ml2.svg";
// const String ml3 = "assets/journey/ml3.svg";
// const String ml4 = "assets/journey/ml4.svg";
// const String ml5 = "assets/journey/ml5.svg";
// const String ml6 = "assets/journey/ml6.svg";
// const String ml7 = "assets/journey/ml7.svg";

// const String mls2 = "assets/journey/mls2.svg";
// const String mls4 = "assets/journey/mls4.svg";
// const String mls5 = "assets/journey/mls5.svg";
// const String mls6 = "assets/journey/mls6.svg";
// const String mls7 = "assets/journey/mls7.svg";

// List<JourneyPage> get jourenyPages => [
//       JourneyPage(
//         bgImage: "assets/journey/bg.svg",
//         page: 1,
//         level: 1,
//         path: [
//           JourneyPathModel(
//             asset: base1,
//             dx: 0.3305,
//             dy: 0.0991,
//             page: 1,
//             width: 0.2873,
//             height: 0.0985,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: "SVG",
//           ),
//           JourneyPathModel(
//             asset: path1,
//             dx: 0.0613,
//             dy: 0.1584,
//             page: 1,
//             width: 0.5262,
//             height: 0.1549,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path2,
//             dx: 0.0705,
//             dy: 0.2813,
//             page: 1,
//             width: 0.2674,
//             height: 0.0991,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base2,
//             dx: 0.1991,
//             dy: 0.3332,
//             page: 1,
//             width: 0.435,
//             height: 0.1314,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.3653,
//             dy: 0.421,
//             page: 1,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base3,
//             dx: 0.6106,
//             dy: 0.5247,
//             page: 1,
//             width: 0.2948,
//             height: 0.0894,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path4,
//             dx: 0.356,
//             dy: 0.5794,
//             page: 1,
//             width: 0.3674,
//             height: 0.1151,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base4,
//             dx: 0.2053,
//             dy: 0.6548,
//             page: 1,
//             width: 0.2598,
//             height: 0.0847,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path5,
//             dx: 0.2213,
//             dy: 0.7167,
//             page: 1,
//             width: 0.0696,
//             height: 0.1046,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base5,
//             dx: 0.008,
//             dy: 0.7973,
//             page: 1,
//             width: 0.3378,
//             height: 0.0992,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path6,
//             dx: 0.216,
//             dy: 0.8596,
//             page: 1,
//             width: 0.4853,
//             height: 0.0677,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base6,
//             dx: 0.624,
//             dy: 0.878,
//             page: 1,
//             width: 0.3386,
//             height: 0.1133,
//             dz: 4,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path7,
//             dx: 0.464,
//             dy: 0.9399,
//             page: 1,
//             width: 0.2805,
//             height: 0.0822,
//             dz: 3,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base7,
//             dx: 0.0906,
//             dy: 0.9418,
//             page: 1,
//             width: 0.4506,
//             height: 0.1382,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//         ],
//         avatarPath: [
//           AvatarPathModel(
//               pathType: "linear", cords: [0.32, 0.8], page: 1, mlIndex: 0),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.24, 0.7], page: 1, mlIndex: 0),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.05, 0.66], page: 1, mlIndex: 0),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.33, 0.58], page: 1, mlIndex: 0),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.48, 0.55], page: 1, mlIndex: 1),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.7, 0.41], page: 1, mlIndex: 1),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.42, 0.32], page: 1, mlIndex: 2),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.26, 0.3], page: 1, mlIndex: 2),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.26, 0.17], page: 1, mlIndex: 3),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.12, 0.14], page: 1, mlIndex: 3),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.08, 0.1], page: 1, mlIndex: 4),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.65, 0.05], page: 1, mlIndex: 4),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.7, 0.03], page: 1, mlIndex: 5),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.58, 0.0], page: 1, mlIndex: 5),
//         ],
//         milestones: [
//           MilestoneModel(
//               asset: ml1,
//               width: 0.1177,
//               height: 0.0824,
//               dx: 0.43,
//               dy: 0.1528,
//               page: 1,
//               level: 1,
//               animType: "NONE",
//               assetType: "SVG",
//               description:
//                   "Watch Walkthrough and win 100 Tokens to get started!",
//               rewards: [
//                 Reward(value: 100, type: "FLC"),
//               ],
//               route: "/walkthrough",
//               isCompleted: true),
//           MilestoneModel(
//             asset: ml2,
//             width: 0.1491,
//             height: 0.0816,
//             dx: 0.348,
//             dy: 0.3966,
//             page: 1,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Complete your profile and get 200 Tokens and ₹50",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//             shadow: MilestoneShadowModel(
//               asset: mls2,
//               width: 0.1225,
//               height: 0.0308,
//               dx: 0.3616,
//               dy: 0.3877,
//               level: 1,
//               page: 1,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml3,
//             width: 0.1158,
//             height: 0.094,
//             dx: 0.704,
//             dy: 0.5673,
//             page: 1,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//           ),
//           MilestoneModel(
//             asset: ml4,
//             width: 0.1107,
//             height: 0.0591,
//             dx: 0.2795,
//             dy: 0.707,
//             page: 1,
//             level: 1,
//             animType: "ROTATE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls4,
//               width: 0.0775,
//               height: 0.0327,
//               dx: 0.2692,
//               dy: 0.6939,
//               level: 1,
//               page: 1,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml5,
//             width: 0.1573,
//             height: 0.0801,
//             dx: 0.0826,
//             dy: 0.8397,
//             page: 1,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls5,
//               width: 0.1513,
//               height: 0.0403,
//               dx: 0.08,
//               dy: 0.8291,
//               level: 1,
//               page: 1,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml6,
//             width: 0.1449,
//             height: 0.1629,
//             dx: 0.712,
//             dy: 0.9121,
//             page: 1,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls6,
//               width: 0.0714,
//               height: 0.0123,
//               dx: 0.7475,
//               dy: 0.9191,
//               level: 1,
//               page: 1,
//             ),
//           ),
//         ],
//       ),
//       JourneyPage(
//         bgImage: "assets/journey/bg.svg",
//         page: 2,
//         level: 1,
//         path: [
//           JourneyPathModel(
//             asset: path8,
//             dx: 0.3973,
//             dy: 0.0419,
//             page: 2,
//             width: 0.2961,
//             height: 0.0947,
//             dz: 1,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base3,
//             dx: 0.56,
//             dy: 0.0985,
//             page: 2,
//             width: 0.2948,
//             height: 0.0894,
//             dz: 3,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.304,
//             dy: 0.1526,
//             page: 2,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 2,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//             hFlip: true,
//           ),
//           JourneyPathModel(
//             asset: base4,
//             dx: 0.2773,
//             dy: 0.2512,
//             page: 2,
//             width: 0.2598,
//             height: 0.0847,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path5,
//             dx: 0.3053,
//             dy: 0.3115,
//             page: 2,
//             width: 0.0696,
//             height: 0.1046,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base5,
//             dx: 0.092,
//             dy: 0.3921,
//             page: 2,
//             width: 0.3378,
//             height: 0.0992,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//               asset: path4,
//               dx: 0.2853,
//               dy: 0.4525,
//               page: 2,
//               width: 0.3674,
//               height: 0.1151,
//               dz: 1,
//               level: 1,
//               isBase: false,
//               source: "AST",
//               type: 'SVG',
//               hFlip: true),
//           JourneyPathModel(
//               asset: base7,
//               dx: 0.4933,
//               dy: 0.5021,
//               page: 2,
//               width: 0.4506,
//               height: 0.1382,
//               dz: 2,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//               hFlip: true),
//           JourneyPathModel(
//             asset: path1,
//             dx: 0.2506,
//             dy: 0.5901,
//             page: 2,
//             width: 0.5262,
//             height: 0.1549,
//             dz: 1,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path2,
//             dx: 0.26,
//             dy: 0.7142,
//             page: 2,
//             width: 0.2674,
//             height: 0.0991,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base4,
//             dx: 0.4213,
//             dy: 0.7711,
//             page: 2,
//             width: 0.2598,
//             height: 0.0847,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.488,
//             dy: 0.8241,
//             page: 2,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base3,
//             dx: 0.704,
//             dy: 0.9204,
//             page: 2,
//             width: 0.2948,
//             height: 0.0894,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path6,
//             dx: 0.2853,
//             dy: 0.9655,
//             page: 2,
//             width: 0.4853,
//             height: 0.0677,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base6,
//             dx: 0.0373,
//             dy: 0.9913,
//             page: 2,
//             width: 0.3386,
//             height: 0.1133,
//             dz: 4,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//         ],
//         avatarPath: [
//           AvatarPathModel(
//               pathType: "linear", cords: [0.26, 0.98], page: 2, mlIndex: 5),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.4, 0.9], page: 2, mlIndex: 6),
//           AvatarPathModel(
//               pathType: "linear", cords: [0.6, 0.84], page: 2, mlIndex: 6),
//         ],
//         milestones: [
//           MilestoneModel(
//             asset: ml7,
//             width: 0.213,
//             height: 0.0868,
//             dx: 0.2106,
//             dy: 0.0207,
//             page: 2,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls7,
//               width: 0.0714,
//               height: 0.0179,
//               dx: 0.336,
//               dy: 0.0115,
//               level: 1,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml3,
//             width: 0.1158,
//             height: 0.094,
//             dx: 0.6534,
//             dy: 0.1325,
//             page: 2,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//           ),
//           MilestoneModel(
//             asset: ml4,
//             width: 0.1107,
//             height: 0.0591,
//             dx: 0.3515,
//             dy: 0.3028,
//             page: 2,
//             level: 1,
//             animType: "ROTATE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls4,
//               width: 0.0775,
//               height: 0.0327,
//               dx: 0.3412,
//               dy: 0.2897,
//               level: 1,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml5,
//             width: 0.1573,
//             height: 0.0801,
//             dx: 0.1667,
//             dy: 0.4346,
//             page: 2,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls5,
//               width: 0.1513,
//               height: 0.0403,
//               dx: 0.164,
//               dy: 0.4239,
//               level: 1,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml7,
//             width: 0.213,
//             height: 0.0868,
//             dx: 0.5786,
//             dy: 0.581,
//             page: 2,
//             level: 1,
//             hFlip: true,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//                 asset: mls7,
//                 width: 0.0714,
//                 height: 0.0179,
//                 dx: 0.6272,
//                 dy: 0.5719,
//                 level: 1,
//                 page: 2,
//                 hFlip: true),
//           ),
//           MilestoneModel(
//             asset: ml4,
//             width: 0.1107,
//             height: 0.0591,
//             dx: 0.4929,
//             dy: 0.8213,
//             page: 2,
//             level: 1,
//             animType: "ROTATE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls4,
//               width: 0.0775,
//               height: 0.0327,
//               dx: 0.4826,
//               dy: 0.8082,
//               level: 1,
//               page: 2,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml2,
//             width: 0.1491,
//             height: 0.0816,
//             dx: 0.776,
//             dy: 0.9627,
//             page: 2,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Complete your profile and get 200 Tokens and ₹50",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//             shadow: MilestoneShadowModel(
//               asset: mls2,
//               width: 0.1225,
//               height: 0.0308,
//               dx: 0.7895,
//               dy: 0.9539,
//               level: 1,
//               page: 2,
//             ),
//           ),
//         ],
//       ),
//       JourneyPage(
//           bgImage: "assets/journey/bg.svg",
//           path: [
//             JourneyPathModel(
//               asset: path3,
//               dx: 0.1013,
//               dy: 0.0405,
//               page: 3,
//               width: 0.4905,
//               height: 0.1429,
//               dz: 1,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base1,
//               dx: 0.3305,
//               dy: 0.0991,
//               page: 3,
//               width: 0.2873,
//               height: 0.0985,
//               dz: 2,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: "SVG",
//             ),
//             JourneyPathModel(
//               asset: path1,
//               dx: 0.0613,
//               dy: 0.1584,
//               page: 3,
//               width: 0.5262,
//               height: 0.1549,
//               dz: 1,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: path2,
//               dx: 0.0705,
//               dy: 0.2813,
//               page: 3,
//               width: 0.2674,
//               height: 0.0991,
//               dz: 0,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base2,
//               dx: 0.1991,
//               dy: 0.3332,
//               page: 3,
//               width: 0.435,
//               height: 0.1314,
//               dz: 2,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: path3,
//               dx: 0.3653,
//               dy: 0.421,
//               page: 3,
//               width: 0.4905,
//               height: 0.1429,
//               dz: 1,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base3,
//               dx: 0.6106,
//               dy: 0.5247,
//               page: 3,
//               width: 0.2948,
//               height: 0.0894,
//               dz: 2,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: path4,
//               dx: 0.356,
//               dy: 0.5794,
//               page: 3,
//               width: 0.3674,
//               height: 0.1151,
//               dz: 1,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base4,
//               dx: 0.2053,
//               dy: 0.6548,
//               page: 3,
//               width: 0.2598,
//               height: 0.0847,
//               dz: 0,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: path5,
//               dx: 0.2213,
//               dy: 0.7167,
//               page: 3,
//               width: 0.0696,
//               height: 0.1046,
//               dz: 0,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base5,
//               dx: 0.008,
//               dy: 0.7973,
//               page: 3,
//               width: 0.3378,
//               height: 0.0992,
//               dz: 0,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: path6,
//               dx: 0.216,
//               dy: 0.8596,
//               page: 3,
//               width: 0.4853,
//               height: 0.0677,
//               dz: 0,
//               level: 1,
//               isBase: false,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base6,
//               dx: 0.624,
//               dy: 0.878,
//               page: 3,
//               width: 0.3386,
//               height: 0.1133,
//               dz: 4,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: path7,
//               dx: 0.464,
//               dy: 0.9399,
//               page: 3,
//               width: 0.2805,
//               height: 0.0822,
//               dz: 3,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//             JourneyPathModel(
//               asset: base7,
//               dx: 0.0906,
//               dy: 0.9418,
//               page: 3,
//               width: 0.4506,
//               height: 0.1382,
//               dz: 2,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//             ),
//           ],
//           page: 3,
//           level: 1,
//           avatarPath: [],
//           milestones: [
//             MilestoneModel(
//               asset: ml6,
//               width: 0.1449,
//               height: 0.1629,
//               dx: 0.143,
//               dy: 0.0247,
//               page: 3,
//               level: 1,
//               animType: "FLOAT",
//               assetType: "SVG",
//               description: "Do some task",
//               rewards: [
//                 Reward(value: 200, type: "FLC"),
//                 Reward(value: 50, type: "Money"),
//               ],
//               route: "/task",
//               shadow: MilestoneShadowModel(
//                 asset: mls6,
//                 width: 0.0714,
//                 height: 0.0123,
//                 dx: 0.1762,
//                 dy: 0.0324,
//                 level: 1,
//                 page: 3,
//               ),
//             ),
//             MilestoneModel(
//                 asset: ml1,
//                 width: 0.1177,
//                 height: 0.0824,
//                 dx: 0.43,
//                 dy: 0.1528,
//                 page: 3,
//                 level: 1,
//                 animType: "NONE",
//                 assetType: "SVG",
//                 description:
//                     "Watch Walkthrough and win 100 Tokens to get started!",
//                 rewards: [
//                   Reward(value: 100, type: "FLC"),
//                 ],
//                 route: "/walkthrough",
//                 isCompleted: true),
//             MilestoneModel(
//               asset: ml2,
//               width: 0.1491,
//               height: 0.0816,
//               dx: 0.348,
//               dy: 0.3966,
//               page: 3,
//               level: 1,
//               animType: "FLOAT",
//               assetType: "SVG",
//               description: "Complete your profile and get 200 Tokens and ₹50",
//               rewards: [
//                 Reward(value: 200, type: "FLC"),
//                 Reward(value: 50, type: "Money"),
//               ],
//               route: "/profile",
//               shadow: MilestoneShadowModel(
//                 asset: mls2,
//                 width: 0.1225,
//                 height: 0.0308,
//                 dx: 0.3616,
//                 dy: 0.3877,
//                 level: 1,
//                 page: 3,
//               ),
//             ),
//             MilestoneModel(
//               asset: ml3,
//               width: 0.1158,
//               height: 0.094,
//               dx: 0.704,
//               dy: 0.5673,
//               page: 3,
//               level: 1,
//               animType: "FLOAT",
//               assetType: "SVG",
//               description: "Do some task",
//               rewards: [
//                 Reward(value: 200, type: "FLC"),
//                 Reward(value: 50, type: "Money"),
//               ],
//               route: "/profile",
//             ),
//             MilestoneModel(
//               asset: ml4,
//               width: 0.1107,
//               height: 0.0591,
//               dx: 0.2795,
//               dy: 0.707,
//               page: 3,
//               level: 1,
//               animType: "ROTATE",
//               assetType: "SVG",
//               description: "Do some task",
//               rewards: [
//                 Reward(value: 200, type: "FLC"),
//                 Reward(value: 50, type: "Money"),
//               ],
//               route: "/task",
//               shadow: MilestoneShadowModel(
//                 asset: mls4,
//                 width: 0.0775,
//                 height: 0.0327,
//                 dx: 0.2692,
//                 dy: 0.6939,
//                 level: 1,
//                 page: 3,
//               ),
//             ),
//             MilestoneModel(
//               asset: ml5,
//               width: 0.1573,
//               height: 0.0801,
//               dx: 0.0826,
//               dy: 0.8397,
//               page: 3,
//               level: 1,
//               animType: "NONE",
//               assetType: "SVG",
//               description: "Do some task",
//               rewards: [
//                 Reward(value: 200, type: "FLC"),
//                 Reward(value: 50, type: "Money"),
//               ],
//               route: "/task",
//               shadow: MilestoneShadowModel(
//                 asset: mls5,
//                 width: 0.1513,
//                 height: 0.0403,
//                 dx: 0.08,
//                 dy: 0.8291,
//                 level: 1,
//                 page: 3,
//               ),
//             ),
//             MilestoneModel(
//               asset: ml6,
//               width: 0.1449,
//               height: 0.1629,
//               dx: 0.712,
//               dy: 0.9121,
//               page: 3,
//               level: 1,
//               animType: "FLOAT",
//               assetType: "SVG",
//               description: "Do some task",
//               rewards: [
//                 Reward(value: 200, type: "FLC"),
//                 Reward(value: 50, type: "Money"),
//               ],
//               route: "/task",
//               shadow: MilestoneShadowModel(
//                 asset: mls6,
//                 width: 0.0714,
//                 height: 0.0123,
//                 dx: 0.7475,
//                 dy: 0.9191,
//                 level: 1,
//                 page: 3,
//               ),
//             ),
//           ]),
//       JourneyPage(
//         bgImage: "assets/journey/bg.svg",
//         path: [
//           JourneyPathModel(
//             asset: path8,
//             dx: 0.3973,
//             dy: 0.0419,
//             page: 4,
//             width: 0.2961,
//             height: 0.0947,
//             dz: 1,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base3,
//             dx: 0.56,
//             dy: 0.0985,
//             page: 4,
//             width: 0.2948,
//             height: 0.0894,
//             dz: 3,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.304,
//             dy: 0.1526,
//             page: 4,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 2,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//             hFlip: true,
//           ),
//           JourneyPathModel(
//             asset: base4,
//             dx: 0.2773,
//             dy: 0.2512,
//             page: 4,
//             width: 0.2598,
//             height: 0.0847,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path5,
//             dx: 0.3053,
//             dy: 0.3115,
//             page: 4,
//             width: 0.0696,
//             height: 0.1046,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base5,
//             dx: 0.092,
//             dy: 0.3921,
//             page: 4,
//             width: 0.3378,
//             height: 0.0992,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//               asset: path4,
//               dx: 0.2853,
//               dy: 0.4525,
//               page: 4,
//               width: 0.3674,
//               height: 0.1151,
//               dz: 1,
//               level: 1,
//               isBase: false,
//               source: "AST",
//               type: 'SVG',
//               hFlip: true),
//           JourneyPathModel(
//               asset: base7,
//               dx: 0.4933,
//               dy: 0.5021,
//               page: 4,
//               width: 0.4506,
//               height: 0.1382,
//               dz: 2,
//               level: 1,
//               isBase: true,
//               source: "AST",
//               type: 'SVG',
//               hFlip: true),
//           JourneyPathModel(
//             asset: path1,
//             dx: 0.2506,
//             dy: 0.5901,
//             page: 4,
//             width: 0.5262,
//             height: 0.1549,
//             dz: 1,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path2,
//             dx: 0.26,
//             dy: 0.7142,
//             page: 4,
//             width: 0.2674,
//             height: 0.0991,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base4,
//             dx: 0.4213,
//             dy: 0.7711,
//             page: 4,
//             width: 0.2598,
//             height: 0.0847,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.488,
//             dy: 0.8241,
//             page: 4,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base3,
//             dx: 0.704,
//             dy: 0.9204,
//             page: 4,
//             width: 0.2948,
//             height: 0.0894,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path6,
//             dx: 0.2853,
//             dy: 0.9655,
//             page: 4,
//             width: 0.4853,
//             height: 0.0677,
//             dz: 0,
//             level: 1,
//             isBase: false,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base6,
//             dx: 0.0373,
//             dy: 0.9913,
//             page: 4,
//             width: 0.3386,
//             height: 0.1133,
//             dz: 4,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//         ],
//         page: 4,
//         level: 1,
//         avatarPath: [],
//         milestones: [
//           MilestoneModel(
//             asset: ml7,
//             width: 0.213,
//             height: 0.0868,
//             dx: 0.2106,
//             dy: 0.0207,
//             page: 4,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls7,
//               width: 0.0714,
//               height: 0.0179,
//               dx: 0.336,
//               dy: 0.0115,
//               level: 1,
//               page: 4,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml3,
//             width: 0.1158,
//             height: 0.094,
//             dx: 0.6534,
//             dy: 0.1325,
//             page: 4,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//           ),
//           MilestoneModel(
//             asset: ml4,
//             width: 0.1107,
//             height: 0.0591,
//             dx: 0.3515,
//             dy: 0.3028,
//             page: 4,
//             level: 1,
//             animType: "ROTATE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls4,
//               width: 0.0775,
//               height: 0.0327,
//               dx: 0.3412,
//               dy: 0.2897,
//               level: 1,
//               page: 4,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml5,
//             width: 0.1573,
//             height: 0.0801,
//             dx: 0.1667,
//             dy: 0.4346,
//             page: 4,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls5,
//               width: 0.1513,
//               height: 0.0403,
//               dx: 0.164,
//               dy: 0.4239,
//               level: 1,
//               page: 4,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml7,
//             width: 0.213,
//             height: 0.0868,
//             dx: 0.5786,
//             dy: 0.581,
//             page: 4,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             hFlip: true,
//             shadow: MilestoneShadowModel(
//                 asset: mls7,
//                 width: 0.0714,
//                 height: 0.0179,
//                 dx: 0.6272,
//                 dy: 0.5719,
//                 level: 1,
//                 page: 4,
//                 hFlip: true),
//           ),
//           MilestoneModel(
//             asset: ml4,
//             width: 0.1107,
//             height: 0.0591,
//             dx: 0.4929,
//             dy: 0.8213,
//             page: 4,
//             level: 1,
//             animType: "ROTATE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls4,
//               width: 0.0775,
//               height: 0.0327,
//               dx: 0.4826,
//               dy: 0.8082,
//               level: 1,
//               page: 4,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml2,
//             width: 0.1491,
//             height: 0.0816,
//             dx: 0.776,
//             dy: 0.9627,
//             page: 4,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Complete your profile and get 200 Tokens and ₹50",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//             shadow: MilestoneShadowModel(
//               asset: mls2,
//               width: 0.1225,
//               height: 0.0308,
//               dx: 0.7895,
//               dy: 0.9539,
//               level: 1,
//               page: 4,
//             ),
//           ),
//         ],
//       ),
//       JourneyPage(
//         bgImage: "assets/journey/bg.svg",
//         path: [
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.1013,
//             dy: 0.0405,
//             page: 5,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base1,
//             dx: 0.3305,
//             dy: 0.0991,
//             page: 5,
//             width: 0.2873,
//             height: 0.0985,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: "SVG",
//           ),
//           JourneyPathModel(
//             asset: path1,
//             dx: 0.0613,
//             dy: 0.1584,
//             page: 5,
//             width: 0.5262,
//             height: 0.1549,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path2,
//             dx: 0.0705,
//             dy: 0.2813,
//             page: 5,
//             width: 0.2674,
//             height: 0.0991,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base2,
//             dx: 0.1991,
//             dy: 0.3332,
//             page: 5,
//             width: 0.435,
//             height: 0.1314,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path3,
//             dx: 0.3653,
//             dy: 0.421,
//             page: 5,
//             width: 0.4905,
//             height: 0.1429,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base3,
//             dx: 0.6106,
//             dy: 0.5247,
//             page: 5,
//             width: 0.2948,
//             height: 0.0894,
//             dz: 2,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path4,
//             dx: 0.356,
//             dy: 0.5794,
//             page: 5,
//             width: 0.3674,
//             height: 0.1151,
//             dz: 1,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base4,
//             dx: 0.2053,
//             dy: 0.6548,
//             page: 5,
//             width: 0.2598,
//             height: 0.0847,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: path5,
//             dx: 0.2213,
//             dy: 0.7167,
//             page: 5,
//             width: 0.0696,
//             height: 0.1046,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//           JourneyPathModel(
//             asset: base5,
//             dx: 0.008,
//             dy: 0.7973,
//             page: 5,
//             width: 0.3378,
//             height: 0.0992,
//             dz: 0,
//             level: 1,
//             isBase: true,
//             source: "AST",
//             type: 'SVG',
//           ),
//         ],
//         page: 5,
//         level: 2,
//         avatarPath: [],
//         milestones: [
//           MilestoneModel(
//             asset: ml6,
//             width: 0.1449,
//             height: 0.1629,
//             dx: 0.143,
//             dy: 0.0247,
//             page: 5,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls6,
//               width: 0.0714,
//               height: 0.0123,
//               dx: 0.1762,
//               dy: 0.0324,
//               level: 1,
//               page: 5,
//             ),
//           ),
//           MilestoneModel(
//               asset: ml1,
//               width: 0.1177,
//               height: 0.0824,
//               dx: 0.43,
//               dy: 0.1528,
//               page: 5,
//               level: 1,
//               animType: "NONE",
//               assetType: "SVG",
//               description:
//                   "Watch Walkthrough and win 100 Tokens to get started!",
//               rewards: [
//                 Reward(value: 100, type: "FLC"),
//               ],
//               route: "/walkthrough",
//               isCompleted: true),
//           MilestoneModel(
//             asset: ml2,
//             width: 0.1491,
//             height: 0.0816,
//             dx: 0.348,
//             dy: 0.3966,
//             page: 5,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Complete your profile and get 200 Tokens and ₹50",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//             shadow: MilestoneShadowModel(
//               asset: mls2,
//               width: 0.1225,
//               height: 0.0308,
//               dx: 0.3616,
//               dy: 0.3877,
//               level: 1,
//               page: 5,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml3,
//             width: 0.1158,
//             height: 0.094,
//             dx: 0.704,
//             dy: 0.5673,
//             page: 5,
//             level: 1,
//             animType: "FLOAT",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/profile",
//           ),
//           MilestoneModel(
//             asset: ml4,
//             width: 0.1107,
//             height: 0.0591,
//             dx: 0.2795,
//             dy: 0.707,
//             page: 5,
//             level: 1,
//             animType: "ROTATE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls4,
//               width: 0.0775,
//               height: 0.0327,
//               dx: 0.2692,
//               dy: 0.6939,
//               level: 1,
//               page: 5,
//             ),
//           ),
//           MilestoneModel(
//             asset: ml5,
//             width: 0.1573,
//             height: 0.0801,
//             dx: 0.0826,
//             dy: 0.8397,
//             page: 5,
//             level: 1,
//             animType: "NONE",
//             assetType: "SVG",
//             description: "Do some task",
//             rewards: [
//               Reward(value: 200, type: "FLC"),
//               Reward(value: 50, type: "Money"),
//             ],
//             route: "/task",
//             shadow: MilestoneShadowModel(
//               asset: mls5,
//               width: 0.1513,
//               height: 0.0403,
//               dx: 0.08,
//               dy: 0.8291,
//               level: 1,
//               page: 5,
//             ),
//           ),
//         ],
//       )
//     ];
