import 'package:felloapp/core/model/golden_ticket_model.dart';
import 'package:felloapp/core/model/journey_models/avatar_path_model.dart';
import 'package:felloapp/core/model/journey_models/journey_asset_model.dart';
import 'package:felloapp/core/model/journey_models/journey_background_model.dart';
import 'package:felloapp/core/model/journey_models/journey_page_model.dart';
import 'package:felloapp/core/model/journey_models/journey_path_model.dart';
import 'package:felloapp/core/model/journey_models/milestone_description.dart';
import 'package:felloapp/core/model/journey_models/milestone_model.dart';
import 'package:flutter/material.dart';

const String path1 = "assets/journey/p1.svg";
const String path2 = "assets/journey/p2.svg";
const String path3 = "assets/journey/p3.svg";
const String path4 = "assets/journey/p4.svg";
const String path5 = "assets/journey/p5.svg";
const String path6 = "assets/journey/p6.svg";
const String path7 = "assets/journey/p7.svg";
const String path8 = "assets/journey/p8.svg";
const String path9 = "assets/journey/p9.svg";
const String path10 = "assets/journey/p10.svg";

const String base1 = "assets/journey/b1.svg";
const String base2 = "assets/journey/b2.svg";
const String base3 = "assets/journey/b3.svg";
const String base4 = "assets/journey/b4.svg";
const String base5 = "assets/journey/b5.svg";
const String base6 = "assets/journey/b6.svg";
const String base7 = "assets/journey/b7.svg";
const String base8 = "assets/journey/b8.svg";
const String base9 = "assets/journey/b9.svg";
const String base10 = "assets/journey/b10.svg";
const String base11 = "assets/journey/b11.svg";

const String ml1 = "assets/journey/m1.svg";
const String ml2 = "assets/journey/m2.svg";
const String ml3 = "assets/journey/m3.svg";
const String ml4 = "assets/journey/m4.svg";
const String ml5 = "assets/journey/m5.svg";
const String ml6 = "assets/journey/m6.svg";
const String ml7 = "assets/journey/m7.svg";
const String ml8 = "assets/journey/m8.svg";
const String ml9 = "assets/journey/m9.svg";
const String ml10 = "assets/journey/m10.svg";

const String mls1 = "assets/journey/ms1.svg";
const String mls2 = "assets/journey/ms2.svg";
const String mls3 = "assets/journey/ms3.svg";
const String mls4 = "assets/journey/ms4.svg";
const String mls5 = "assets/journey/ms5.svg";
const String mls6 = "assets/journey/ms6.svg";
const String mls7 = "assets/journey/ms7.svg";
const String mls8 = "assets/journey/ms8.svg";
const String mls9 = "assets/journey/ms9.svg";
const String mls10 = "assets/journey/ms10.svg";

//counting milestones from 1

List<String> background = [
  'assets/journeypathassets/bg1.svg'
      'assets/journeypathassets/bg2.svg'
      'assets/journeypathassets/bg3.svg'
      'assets/journeypathassets/bg4.svg'
];

List<JourneyPage> get jourenyPages => [
      JourneyPage(
        bgAsset: JourneyBackgroundModel(
          colors: [Color(0xff168A7F), Color(0xff289D88)],
          stops: [0, 1],
          asset: JourneyAssetModel(
              uri: "assets/journey/bg1.svg",
              height: 1,
              width: 1,
              name: 'bg2',
              page: 1,
              assetType: "SVG"),
        ),
        page: 1,
        paths: [
          JourneyPathModel(
            id: 'b1',
            asset: JourneyAssetModel(
              uri: base1,
              width: 0.2731,
              height: 0.0967,
              name: "b1",
              page: 1,
            ),
            x: 0.5066,
            y: 0.2826,
            page: 1,
            z: 4,
            mlIndex: 1,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p1',
            asset: JourneyAssetModel(
              uri: path1,
              width: 0.5163,
              height: 0.152,
              name: "p1",
              page: 1,
            ),
            x: 0.2374,
            y: 0.3434,
            page: 1,
            z: 3,
            mlIndex: 2,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b2',
            asset: JourneyAssetModel(
              uri: base2,
              width: 0.5324,
              height: 0.1447,
              name: "b2",
              page: 1,
            ),
            x: 0.0676,
            y: 0.4516,
            page: 1,
            z: 4,
            mlIndex: 2,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p2',
            asset: JourneyAssetModel(
              uri: path2,
              width: 0.4872,
              height: 0.1678,
              name: "p2",
              page: 1,
            ),
            x: 0.388,
            y: 0.5540,
            page: 1,
            z: 5,
            mlIndex: 3,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b3',
            asset: JourneyAssetModel(
              uri: base3,
              width: 0.5089,
              height: 0.1603,
              name: "b3",
              page: 1,
            ),
            x: 0.3254,
            y: 0.6575,
            page: 1,
            z: 4,
            mlIndex: 3,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p3',
            asset: JourneyAssetModel(
              uri: path3,
              width: 0.5254,
              height: 0.1537,
              name: "p3",
              page: 1,
            ),
            x: 0.1657,
            y: 0.7651,
            page: 1,
            z: 3,
            mlIndex: 4,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b4',
            asset: JourneyAssetModel(
              uri: base4,
              width: 0.2948,
              height: 0.1004,
              name: "b4",
              page: 1,
            ),
            x: 0.1479,
            y: 0.8732,
            page: 1,
            z: 2,
            mlIndex: 4,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p4',
            asset: JourneyAssetModel(
              uri: path4,
              width: 0.5086,
              height: 0.1489,
              name: "p4",
              page: 1,
            ),
            x: 0.2243,
            y: 0.9398,
            page: 1,
            z: 1,
            mlIndex: 5,
            isBase: false,
          ),
        ],
        avatarPath: [
          AvatarPathModel(
              moveType: "linear", coords: [0.53, 0.63], page: 1, mlIndex: 1),
          AvatarPathModel(
              moveType: "linear", coords: [0.4, 0.5], page: 1, mlIndex: 2),
          AvatarPathModel(
              moveType: "linear", coords: [0.2, 0.45], page: 1, mlIndex: 2),
          AvatarPathModel(
              moveType: "linear", coords: [0.73, 0.31], page: 1, mlIndex: 3),
          AvatarPathModel(
              moveType: "linear", coords: [0.5, 0.22], page: 1, mlIndex: 3),
          AvatarPathModel(
              moveType: "linear", coords: [0.32, 0.1], page: 1, mlIndex: 4),
          AvatarPathModel(
              moveType: "linear", coords: [0.18, 0.06], page: 1, mlIndex: 4),
          AvatarPathModel(
              moveType: "linear", coords: [0.3, 0.02], page: 1, mlIndex: 5),
        ],
        milestones: [
          MilestoneModel(
            id: 'm1',
            asset: JourneyAssetModel(
              uri: ml1,
              name: 'm1',
              width: 0.1451,
              height: 0.0794,
              page: 1,
            ),
            x: 0.5669,
            y: 0.3368,
            page: 1,
            index: 1,
            animType: "NONE",
            isCompleted: true,
            steps: [
              MlSteps(
                title: "Watch Walkthrough and win 100 Tokens to get started!",
                subtitle: "Description of the milestone",
              )
            ],
            rewards: [
              Reward(value: 100, type: "FLC"),
            ],
            actionUri: "/walkthrough",
            shadow: MilestoneShadowModel(
              id: 'ms1',
              name: 'ms1',
              asset: JourneyAssetModel(
                uri: mls1,
                width: 0.1331,
                height: 0.0335,
                name: 'ms1',
                page: 1,
              ),
              x: 0.5733,
              y: 0.3283,
              index: 1,
              page: 1,
            ),
          ),
          MilestoneModel(
            id: 'm2',
            asset: JourneyAssetModel(
              uri: ml2,
              name: 'm2',
              width: 0.1605,
              height: 0.0857,
              page: 1,
            ),
            x: 0.263,
            y: 0.5237,
            page: 1,
            index: 2, //index
            animType: "ROTATE",
            isCompleted: true,
            steps: [
              //steps
              MlSteps(
                title: "Complete Your Profile",
                subtitle: "Description of the milestone",
              )
            ],
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/profile",
            shadow: MilestoneShadowModel(
              id: 'ms2',
              name: 'ms2',
              asset: JourneyAssetModel(
                uri: mls2,
                width: 0.1123,
                height: 0.0474,
                name: 'ms2',
                page: 1,
              ),
              x: 0.248,
              y: 0.5047,
              index: 1,
              page: 1,
            ),
          ),
          MilestoneModel(
            id: 'm3',
            asset: JourneyAssetModel(
              uri: ml3,
              name: 'm3',
              width: 0.2134,
              height: 0.0627,
              page: 1,
            ),
            x: 0.5302,
            y: 0.7369,
            page: 1,
            index: 3,
            animType: "FLOAT",
            isCompleted: true,
            steps: [
              MlSteps(
                title: "Play your first game",
                subtitle: "You can play any game you wish",
              )
            ],
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/play",
            shadow: MilestoneShadowModel(
              id: 'ms3',
              name: 'ms3',
              asset: JourneyAssetModel(
                uri: mls3,
                width: 0.0965,
                height: 0.0749,
                name: 'ms3',
                page: 1,
              ),
              x: 0.5206,
              y: 0.7268,
              index: 1,
              page: 1,
            ),
          ),
          MilestoneModel(
            id: 'm4',
            asset: JourneyAssetModel(
              uri: ml4,
              name: 'm4',
              width: 0.142,
              height: 0.0508,
              page: 1,
            ),
            x: 0.2193,
            y: 0.9234,
            page: 1,
            index: 4,
            animType: "FLOAT",
            steps: [
              MlSteps(
                title: "Buy a Tambola Ticket",
                subtitle: "Description of the milestone",
              )
            ],
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/tambolaHome",
            shadow: MilestoneShadowModel(
              id: 'ms4',
              name: 'ms4',
              asset: JourneyAssetModel(
                uri: mls4,
                width: 0.1041,
                height: 0.027,
                name: 'ms4',
                page: 1,
              ),
              x: 0.2152,
              y: 0.9133,
              index: 1,
              page: 1,
            ),
          ),
        ],
      ),
      JourneyPage(
        bgAsset: JourneyBackgroundModel(
          colors: [Color(0xff0C5B62), Color(0xff0C5B62), Color(0xff168A7F)],
          stops: [0, 0.55, 1],
          asset: JourneyAssetModel(
              uri: "assets/journey/bg2.svg",
              height: 1,
              width: 1,
              name: 'bg2',
              page: 2,
              assetType: "SVG"),
        ),
        page: 2,
        paths: [
          JourneyPathModel(
            id: 'b5',
            asset: JourneyAssetModel(
              uri: base5,
              width: 0.4489,
              height: 0.1197,
              name: "b5",
              page: 2,
            ),
            x: 0.4272,
            y: 0.0384,
            page: 2,
            z: 2,
            mlIndex: 5,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p5',
            asset: JourneyAssetModel(
              uri: path5,
              width: 0.2888,
              height: 0.0789,
              name: "p5",
              page: 2,
            ),
            x: 0.2871,
            y: 0.1203,
            page: 2,
            z: 3,
            mlIndex: 6,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b6',
            asset: JourneyAssetModel(
              uri: base6,
              width: 0.3386,
              height: 0.1133,
              name: "b6",
              page: 2,
            ),
            x: 0.0464,
            y: 0.151,
            page: 2,
            z: 2,
            mlIndex: 6,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p6',
            asset: JourneyAssetModel(
              uri: path6,
              width: 0.3436,
              height: 0.098,
              name: "p6",
              page: 2,
            ),
            x: 0.2624,
            y: 0.2213,
            page: 2,
            z: 1,
            mlIndex: 7,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b7',
            asset: JourneyAssetModel(
              uri: base7,
              width: 0.3524,
              height: 0.0978,
              name: "b7",
              page: 2,
            ),
            x: 0.456,
            y: 0.2709,
            page: 2,
            z: 0,
            mlIndex: 7,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p7',
            asset: JourneyAssetModel(
              uri: path7,
              width: 0.251,
              height: 0.1489,
              name: "p7",
              page: 2,
            ),
            x: 0.3025,
            y: 0.3652,
            page: 2,
            z: 0,
            mlIndex: 8,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b8',
            asset: JourneyAssetModel(
              uri: base8,
              width: 0.4463,
              height: 0.1196,
              name: "b3",
              page: 2,
            ),
            x: 0.0981,
            y: 0.4992,
            page: 2,
            z: 4,
            mlIndex: 8,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p8',
            asset: JourneyAssetModel(
              uri: path8,
              width: 0.2681,
              height: 0.0718,
              name: "p8",
              page: 2,
            ),
            mlIndex: 9,
            x: 0.399,
            y: 0.5926,
            page: 2,
            z: 5,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b9',
            asset: JourneyAssetModel(
              uri: base9,
              width: 0.4506,
              height: 0.1431,
              name: "b9",
              page: 2,
            ),
            x: 0.4145,
            y: 0.6269,
            page: 2,
            mlIndex: 9,
            z: 4,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p9',
            asset: JourneyAssetModel(
              uri: path9,
              width: 0.5146,
              height: 0.1562,
              name: "p9",
              page: 2,
            ),
            x: 0.1408,
            y: 0.7213,
            page: 2,
            mlIndex: 10,
            z: 3,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b10',
            asset: JourneyAssetModel(
              uri: base10,
              width: 0.474,
              height: 0.2518,
              name: "b10",
              page: 2,
            ),
            x: 0.0479,
            y: 0.8233,
            page: 2,
            mlIndex: 10,
            z: 2,
            isBase: true,
          ),
          JourneyPathModel(
            id: 'p10',
            asset: JourneyAssetModel(
              uri: path10,
              width: 0.3281,
              height: 0.0855,
              name: "p10",
              page: 2,
            ),
            x: 0.328,
            y: 0.92,
            page: 2,
            mlIndex: 11,
            z: 3,
            isBase: false,
          ),
          JourneyPathModel(
            id: 'b11',
            asset: JourneyAssetModel(
              uri: base11,
              width: 0.3095,
              height: 0.1054,
              name: "b11",
              page: 2,
            ),
            x: 0.5226,
            y: 0.9647,
            page: 2,
            mlIndex: 11,
            z: 2,
            isBase: true,
          ),
        ],
        avatarPath: [
          AvatarPathModel(
              moveType: "linear", coords: [0.5, 0.9], page: 2, mlIndex: 5),
          AvatarPathModel(
              moveType: "linear", coords: [0.65, 0.86], page: 2, mlIndex: 5),
          AvatarPathModel(
              moveType: "linear", coords: [0.12, 0.78], page: 2, mlIndex: 6),
          AvatarPathModel(
              moveType: "linear", coords: [0.55, 0.68], page: 2, mlIndex: 7),
          AvatarPathModel(
              moveType: "linear", coords: [0.2, 0.42], page: 2, mlIndex: 8),
          AvatarPathModel(
              moveType: "linear", coords: [0.6, 0.28], page: 2, mlIndex: 9),
          AvatarPathModel(
              moveType: "linear", coords: [0.35, 0.15], page: 2, mlIndex: 10),
          AvatarPathModel(
              moveType: "linear", coords: [0.15, 0.1], page: 2, mlIndex: 10),
          AvatarPathModel(
              moveType: "linear", coords: [0.5, 0.0], page: 2, mlIndex: 11),
        ],
        milestones: [
          MilestoneModel(
            id: 'm5',
            asset: JourneyAssetModel(
              uri: ml5,
              name: 'm5',
              width: 0.2143,
              height: 0.1026,
              page: 2,
            ),
            x: 0.5451,
            y: 0.1048,
            page: 2,
            index: 5,
            animType: "NONE",
            steps: [
              MlSteps(
                title: "Explore about Digital Gold",
                subtitle: "Check out our Digital Gold Asset",
              )
            ],
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/goldDetails",
            shadow: MilestoneShadowModel(
              id: 'ms5',
              name: 'ms5',
              asset: JourneyAssetModel(
                uri: mls5,
                width: 0.0894,
                height: 0.0177,
                page: 2,
                name: 'ms5',
              ),
              x: 0.602,
              y: 0.095,
              index: 5,
              page: 2,
            ),
          ),
          MilestoneModel(
            id: 'm6',
            asset: JourneyAssetModel(
              uri: ml6,
              name: 'm6',
              width: 0.1825,
              height: 0.0777,
              page: 2,
            ),
            x: 0.1505,
            y: 0.1924,
            page: 2,
            index: 6,
            animType: "FLOAT",
            steps: [
              MlSteps(
                title: "Make your first Digital Gold Savings",
                subtitle: "Description of the milestone",
              )
            ],
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/save",
            shadow: MilestoneShadowModel(
              id: 'ms6',
              name: 'ms6',
              asset: JourneyAssetModel(
                uri: mls6,
                width: 0.1063,
                height: 0.0453,
                name: 'ms6',
                page: 2,
              ),
              x: 0.1542,
              y: 0.1925,
              index: 6,
              page: 2,
            ),
          ),
          MilestoneModel(
            id: 'm7',
            asset: JourneyAssetModel(
              uri: ml7,
              name: 'm7',
              width: 0.203,
              height: 0.0919,
              page: 2,
            ),
            steps: [
              MlSteps(
                title: "Complete a Daily Challenge",
                subtitle: "Description of the milestone",
              )
            ],
            x: 0.5457,
            y: 0.3002,
            page: 2,
            index: 7,
            animType: "NONE",
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/win",
            shadow: MilestoneShadowModel(
              id: 'ms7',
              name: 'ms7',
              asset: JourneyAssetModel(
                uri: mls7,
                name: 'ms7',
                width: 0.0894,
                height: 0.0177,
                page: 2,
              ),
              x: 0.5696,
              y: 0.3147,
              index: 7,
              page: 2,
            ),
          ),
          MilestoneModel(
            id: 'm8',
            asset: JourneyAssetModel(
              uri: ml8,
              name: 'm8',
              width: 0.1989,
              height: 0.0925,
              page: 2,
            ),
            steps: [
              MlSteps(
                title: "Make to the weekly leaderboard of Cricket",
                subtitle: "Description of the milestone",
              )
            ],
            x: 0.2352,
            y: 0.5421,
            page: 2,
            index: 8,
            animType: "NONE",
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/play",
            shadow: MilestoneShadowModel(
              id: 'ms8',
              name: 'ms8',
              asset: JourneyAssetModel(
                uri: mls8,
                name: 'ms8',
                width: 0.1542,
                height: 0.0464,
                page: 2,
              ),
              x: 0.1943,
              y: 0.5412,
              index: 7,
              page: 2,
            ),
          ),
          MilestoneModel(
            id: 'm9',
            asset: JourneyAssetModel(
              uri: ml9,
              name: 'm9',
              width: 0.1557,
              height: 0.175,
              page: 2,
            ),
            steps: [
              MlSteps(
                title: "Invite a friend to Fello",
                subtitle: "Description of the milestone",
              )
            ],
            x: 0.517,
            y: 0.7025,
            page: 2,
            index: 9,
            animType: "FLOAT",
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/task",
            shadow: MilestoneShadowModel(
              id: 'ms9',
              name: 'ms9',
              asset: JourneyAssetModel(
                uri: mls9,
                name: 'ms9',
                width: 0.1018,
                height: 0.0142,
                page: 2,
              ),
              x: 0.5354,
              y: 0.7012,
              index: 9,
              page: 2,
            ),
          ),
          MilestoneModel(
            id: 'm10',
            asset: JourneyAssetModel(
              uri: ml10,
              name: 'm10',
              width: 0.1092,
              height: 0.1167,
              page: 2,
            ),
            steps: [
              MlSteps(
                title: "Reach a score of 100 in Fello Cricket",
                subtitle: "Description of the milestone",
              )
            ],
            x: 0.1588,
            y: 0.8642,
            page: 2,
            index: 10,
            animType: "NONE",
            isCompleted: true,
            rewards: [
              Reward(value: 200, type: "FLC"),
              Reward(value: 50, type: "Money"),
            ],
            actionUri: "/cricketHome",
            shadow: MilestoneShadowModel(
              id: 'm10',
              name: 'ms10',
              asset: JourneyAssetModel(
                uri: mls10,
                name: 'ms10',
                width: 0.1461,
                height: 0.037,
                page: 2,
              ),
              x: 0.221,
              y: 0.8748,
              index: 10,
              page: 2,
            ),
          ),
        ],
      ),
      // JourneyPage(
      //     bgImage: "assets/journey/bg.svg",
      //     paths: [
      //       JourneyPathModel(
      //         asset: path3,
      //         x: 0.1013,
      //         y: 0.0405,
      //         page: 3,
      //         width: 0.4905,
      //         height: 0.1429,
      //         z: 1,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base1,
      //         x: 0.3305,
      //         y: 0.0991,
      //         page: 3,
      //         width: 0.2873,
      //         height: 0.0985,
      //         z: 2,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: "SVG",
      //       ),
      //       JourneyPathModel(
      //         asset: path1,
      //         x: 0.0613,
      //         y: 0.1584,
      //         page: 3,
      //         width: 0.5262,
      //         height: 0.1549,
      //         z: 1,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: path2,
      //         x: 0.0705,
      //         y: 0.2813,
      //         page: 3,
      //         width: 0.2674,
      //         height: 0.0991,
      //         z: 0,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base2,
      //         x: 0.1991,
      //         y: 0.3332,
      //         page: 3,
      //         width: 0.435,
      //         height: 0.1314,
      //         z: 2,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: path3,
      //         x: 0.3653,
      //         y: 0.421,
      //         page: 3,
      //         width: 0.4905,
      //         height: 0.1429,
      //         z: 1,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base3,
      //         x: 0.6106,
      //         y: 0.5247,
      //         page: 3,
      //         width: 0.2948,
      //         height: 0.0894,
      //         z: 2,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: path4,
      //         x: 0.356,
      //         y: 0.5794,
      //         page: 3,
      //         width: 0.3674,
      //         height: 0.1151,
      //         z: 1,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base4,
      //         x: 0.2053,
      //         y: 0.6548,
      //         page: 3,
      //         width: 0.2598,
      //         height: 0.0847,
      //         z: 0,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: path5,
      //         x: 0.2213,
      //         y: 0.7167,
      //         page: 3,
      //         width: 0.0696,
      //         height: 0.1046,
      //         z: 0,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base5,
      //         x: 0.008,
      //         y: 0.7973,
      //         page: 3,
      //         width: 0.3378,
      //         height: 0.0992,
      //         z: 0,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: path6,
      //         x: 0.216,
      //         y: 0.8596,
      //         page: 3,
      //         width: 0.4853,
      //         height: 0.0677,
      //         z: 0,
      //         level: 1,
      //         isBase: false,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base6,
      //         x: 0.624,
      //         y: 0.878,
      //         page: 3,
      //         width: 0.3386,
      //         height: 0.1133,
      //         z: 4,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: path7,
      //         x: 0.464,
      //         y: 0.9399,
      //         page: 3,
      //         width: 0.2805,
      //         height: 0.0822,
      //         z: 3,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //       JourneyPathModel(
      //         asset: base7,
      //         x: 0.0906,
      //         y: 0.9418,
      //         page: 3,
      //         width: 0.4506,
      //         height: 0.1382,
      //         z: 2,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //       ),
      //     ],
      //     page: 3,
      //     level: 1,
      //     avatarPath: [],
      //     milestones: [
      //       MilestoneModel(
      //         asset: ml6,
      //         width: 0.1449,
      //         height: 0.1629,
      //         x: 0.143,
      //         y: 0.0247,
      //         page: 3,
      //         level: 1,
      //         animType: "FLOAT",
      //         assetType: "SVG",
      //         description: "Do some task",
      //         rewards: [
      //           Reward(value: 200, type: "FLC"),
      //           Reward(value: 50, type: "Money"),
      //         ],
      //         actionUri: "/task",
      //         shadow: MilestoneShadowModel(
      //           asset: mls6,
      //           width: 0.0714,
      //           height: 0.0123,
      //           x: 0.1762,
      //           y: 0.0324,
      //           level: 1,
      //           page: 3,
      //         ),
      //       ),
      //       MilestoneModel(
      //           asset: ml1,
      //           width: 0.1177,
      //           height: 0.0824,
      //           x: 0.43,
      //           y: 0.1528,
      //           page: 3,
      //           level: 1,
      //           animType: "NONE",
      //           assetType: "SVG",
      //           description:
      //               "Watch Walkthrough and win 100 Tokens to get started!",
      //           rewards: [
      //             Reward(value: 100, type: "FLC"),
      //           ],
      //           actionUri: "/walkthrough",
      //           isCompleted: true),
      //       MilestoneModel(
      //         asset: ml2,
      //         width: 0.1491,
      //         height: 0.0816,
      //         x: 0.348,
      //         y: 0.3966,
      //         page: 3,
      //         level: 1,
      //         animType: "FLOAT",
      //         assetType: "SVG",
      //         description: "Complete your profile and get 200 Tokens and ₹50",
      //         rewards: [
      //           Reward(value: 200, type: "FLC"),
      //           Reward(value: 50, type: "Money"),
      //         ],
      //         actionUri: "/profile",
      //         shadow: MilestoneShadowModel(
      //           asset: mls2,
      //           width: 0.1225,
      //           height: 0.0308,
      //           x: 0.3616,
      //           y: 0.3877,
      //           level: 1,
      //           page: 3,
      //         ),
      //       ),
      //       MilestoneModel(
      //         asset: ml3,
      //         width: 0.1158,
      //         height: 0.094,
      //         x: 0.704,
      //         y: 0.5673,
      //         page: 3,
      //         level: 1,
      //         animType: "FLOAT",
      //         assetType: "SVG",
      //         description: "Do some task",
      //         rewards: [
      //           Reward(value: 200, type: "FLC"),
      //           Reward(value: 50, type: "Money"),
      //         ],
      //         actionUri: "/profile",
      //       ),
      //       MilestoneModel(
      //         asset: ml4,
      //         width: 0.1107,
      //         height: 0.0591,
      //         x: 0.2795,
      //         y: 0.707,
      //         page: 3,
      //         level: 1,
      //         animType: "ROTATE",
      //         assetType: "SVG",
      //         description: "Do some task",
      //         rewards: [
      //           Reward(value: 200, type: "FLC"),
      //           Reward(value: 50, type: "Money"),
      //         ],
      //         actionUri: "/task",
      //         shadow: MilestoneShadowModel(
      //           asset: mls4,
      //           width: 0.0775,
      //           height: 0.0327,
      //           x: 0.2692,
      //           y: 0.6939,
      //           level: 1,
      //           page: 3,
      //         ),
      //       ),
      //       MilestoneModel(
      //         asset: ml5,
      //         width: 0.1573,
      //         height: 0.0801,
      //         x: 0.0826,
      //         y: 0.8397,
      //         page: 3,
      //         level: 1,
      //         animType: "NONE",
      //         assetType: "SVG",
      //         description: "Do some task",
      //         rewards: [
      //           Reward(value: 200, type: "FLC"),
      //           Reward(value: 50, type: "Money"),
      //         ],
      //         actionUri: "/task",
      //         shadow: MilestoneShadowModel(
      //           asset: mls5,
      //           width: 0.1513,
      //           height: 0.0403,
      //           x: 0.08,
      //           y: 0.8291,
      //           level: 1,
      //           page: 3,
      //         ),
      //       ),
      //       MilestoneModel(
      //         asset: ml6,
      //         width: 0.1449,
      //         height: 0.1629,
      //         x: 0.712,
      //         y: 0.9121,
      //         page: 3,
      //         level: 1,
      //         animType: "FLOAT",
      //         assetType: "SVG",
      //         description: "Do some task",
      //         rewards: [
      //           Reward(value: 200, type: "FLC"),
      //           Reward(value: 50, type: "Money"),
      //         ],
      //         actionUri: "/task",
      //         shadow: MilestoneShadowModel(
      //           asset: mls6,
      //           width: 0.0714,
      //           height: 0.0123,
      //           x: 0.7475,
      //           y: 0.9191,
      //           level: 1,
      //           page: 3,
      //         ),
      //       ),
      //     ]),
      // JourneyPage(
      //   bgImage: "assets/journey/bg.svg",
      //   paths: [
      //     JourneyPathModel(
      //       asset: path8,
      //       x: 0.3973,
      //       y: 0.0419,
      //       page: 4,
      //       width: 0.2961,
      //       height: 0.0947,
      //       z: 1,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base3,
      //       x: 0.56,
      //       y: 0.0985,
      //       page: 4,
      //       width: 0.2948,
      //       height: 0.0894,
      //       z: 3,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path3,
      //       x: 0.304,
      //       y: 0.1526,
      //       page: 4,
      //       width: 0.4905,
      //       height: 0.1429,
      //       z: 2,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //       hFlip: true,
      //     ),
      //     JourneyPathModel(
      //       asset: base4,
      //       x: 0.2773,
      //       y: 0.2512,
      //       page: 4,
      //       width: 0.2598,
      //       height: 0.0847,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path5,
      //       x: 0.3053,
      //       y: 0.3115,
      //       page: 4,
      //       width: 0.0696,
      //       height: 0.1046,
      //       z: 0,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base5,
      //       x: 0.092,
      //       y: 0.3921,
      //       page: 4,
      //       width: 0.3378,
      //       height: 0.0992,
      //       z: 2,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //         asset: path4,
      //         x: 0.2853,
      //         y: 0.4525,
      //         page: 4,
      //         width: 0.3674,
      //         height: 0.1151,
      //         z: 1,
      //         level: 1,
      //         isBase: false,
      //         source: "AST",
      //         type: 'SVG',
      //         hFlip: true),
      //     JourneyPathModel(
      //         asset: base7,
      //         x: 0.4933,
      //         y: 0.5021,
      //         page: 4,
      //         width: 0.4506,
      //         height: 0.1382,
      //         z: 2,
      //         level: 1,
      //         isBase: true,
      //         source: "AST",
      //         type: 'SVG',
      //         hFlip: true),
      //     JourneyPathModel(
      //       asset: path1,
      //       x: 0.2506,
      //       y: 0.5901,
      //       page: 4,
      //       width: 0.5262,
      //       height: 0.1549,
      //       z: 1,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path2,
      //       x: 0.26,
      //       y: 0.7142,
      //       page: 4,
      //       width: 0.2674,
      //       height: 0.0991,
      //       z: 0,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base4,
      //       x: 0.4213,
      //       y: 0.7711,
      //       page: 4,
      //       width: 0.2598,
      //       height: 0.0847,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path3,
      //       x: 0.488,
      //       y: 0.8241,
      //       page: 4,
      //       width: 0.4905,
      //       height: 0.1429,
      //       z: 0,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base3,
      //       x: 0.704,
      //       y: 0.9204,
      //       page: 4,
      //       width: 0.2948,
      //       height: 0.0894,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path6,
      //       x: 0.2853,
      //       y: 0.9655,
      //       page: 4,
      //       width: 0.4853,
      //       height: 0.0677,
      //       z: 0,
      //       level: 1,
      //       isBase: false,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base6,
      //       x: 0.0373,
      //       y: 0.9913,
      //       page: 4,
      //       width: 0.3386,
      //       height: 0.1133,
      //       z: 4,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //   ],
      //   page: 4,
      //   level: 1,
      //   avatarPath: [],
      //   milestones: [
      //     MilestoneModel(
      //       asset: ml7,
      //       width: 0.213,
      //       height: 0.0868,
      //       x: 0.2106,
      //       y: 0.0207,
      //       page: 4,
      //       level: 1,
      //       animType: "NONE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls7,
      //         width: 0.0714,
      //         height: 0.0179,
      //         x: 0.336,
      //         y: 0.0115,
      //         level: 1,
      //         page: 4,
      //       ),
      //     ),
      //     MilestoneModel(
      //       asset: ml3,
      //       width: 0.1158,
      //       height: 0.094,
      //       x: 0.6534,
      //       y: 0.1325,
      //       page: 4,
      //       level: 1,
      //       animType: "FLOAT",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/profile",
      //     ),
      //     MilestoneModel(
      //       asset: ml4,
      //       width: 0.1107,
      //       height: 0.0591,
      //       x: 0.3515,
      //       y: 0.3028,
      //       page: 4,
      //       level: 1,
      //       animType: "ROTATE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls4,
      //         width: 0.0775,
      //         height: 0.0327,
      //         x: 0.3412,
      //         y: 0.2897,
      //         level: 1,
      //         page: 4,
      //       ),
      //     ),
      //     MilestoneModel(
      //       asset: ml5,
      //       width: 0.1573,
      //       height: 0.0801,
      //       x: 0.1667,
      //       y: 0.4346,
      //       page: 4,
      //       level: 1,
      //       animType: "NONE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls5,
      //         width: 0.1513,
      //         height: 0.0403,
      //         x: 0.164,
      //         y: 0.4239,
      //         level: 1,
      //         page: 4,
      //       ),
      //     ),
      //     MilestoneModel(
      //       asset: ml7,
      //       width: 0.213,
      //       height: 0.0868,
      //       x: 0.5786,
      //       y: 0.581,
      //       page: 4,
      //       level: 1,
      //       animType: "NONE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       hFlip: true,
      //       shadow: MilestoneShadowModel(
      //           asset: mls7,
      //           width: 0.0714,
      //           height: 0.0179,
      //           x: 0.6272,
      //           y: 0.5719,
      //           level: 1,
      //           page: 4,
      //           hFlip: true),
      //     ),
      //     MilestoneModel(
      //       asset: ml4,
      //       width: 0.1107,
      //       height: 0.0591,
      //       x: 0.4929,
      //       y: 0.8213,
      //       page: 4,
      //       level: 1,
      //       animType: "ROTATE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls4,
      //         width: 0.0775,
      //         height: 0.0327,
      //         x: 0.4826,
      //         y: 0.8082,
      //         level: 1,
      //         page: 4,
      //       ),
      //     ),
      //     MilestoneModel(
      //       asset: ml2,
      //       width: 0.1491,
      //       height: 0.0816,
      //       x: 0.776,
      //       y: 0.9627,
      //       page: 4,
      //       level: 1,
      //       animType: "FLOAT",
      //       assetType: "SVG",
      //       description: "Complete your profile and get 200 Tokens and ₹50",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/profile",
      //       shadow: MilestoneShadowModel(
      //         asset: mls2,
      //         width: 0.1225,
      //         height: 0.0308,
      //         x: 0.7895,
      //         y: 0.9539,
      //         level: 1,
      //         page: 4,
      //       ),
      //     ),
      //   ],
      // ),
      // JourneyPage(
      //   bgImage: "assets/journey/bg.svg",
      //   paths: [
      //     JourneyPathModel(
      //       asset: path3,
      //       x: 0.1013,
      //       y: 0.0405,
      //       page: 5,
      //       width: 0.4905,
      //       height: 0.1429,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base1,
      //       x: 0.3305,
      //       y: 0.0991,
      //       page: 5,
      //       width: 0.2873,
      //       height: 0.0985,
      //       z: 2,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: "SVG",
      //     ),
      //     JourneyPathModel(
      //       asset: path1,
      //       x: 0.0613,
      //       y: 0.1584,
      //       page: 5,
      //       width: 0.5262,
      //       height: 0.1549,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path2,
      //       x: 0.0705,
      //       y: 0.2813,
      //       page: 5,
      //       width: 0.2674,
      //       height: 0.0991,
      //       z: 0,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base2,
      //       x: 0.1991,
      //       y: 0.3332,
      //       page: 5,
      //       width: 0.435,
      //       height: 0.1314,
      //       z: 2,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path3,
      //       x: 0.3653,
      //       y: 0.421,
      //       page: 5,
      //       width: 0.4905,
      //       height: 0.1429,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base3,
      //       x: 0.6106,
      //       y: 0.5247,
      //       page: 5,
      //       width: 0.2948,
      //       height: 0.0894,
      //       z: 2,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path4,
      //       x: 0.356,
      //       y: 0.5794,
      //       page: 5,
      //       width: 0.3674,
      //       height: 0.1151,
      //       z: 1,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base4,
      //       x: 0.2053,
      //       y: 0.6548,
      //       page: 5,
      //       width: 0.2598,
      //       height: 0.0847,
      //       z: 0,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: path5,
      //       x: 0.2213,
      //       y: 0.7167,
      //       page: 5,
      //       width: 0.0696,
      //       height: 0.1046,
      //       z: 0,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //     JourneyPathModel(
      //       asset: base5,
      //       x: 0.008,
      //       y: 0.7973,
      //       page: 5,
      //       width: 0.3378,
      //       height: 0.0992,
      //       z: 0,
      //       level: 1,
      //       isBase: true,
      //       source: "AST",
      //       type: 'SVG',
      //     ),
      //   ],
      //   page: 5,
      //   level: 2,
      //   avatarPath: [],
      //   milestones: [
      //     MilestoneModel(
      //       asset: ml6,
      //       width: 0.1449,
      //       height: 0.1629,
      //       x: 0.143,
      //       y: 0.0247,
      //       page: 5,
      //       level: 1,
      //       animType: "FLOAT",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls6,
      //         width: 0.0714,
      //         height: 0.0123,
      //         x: 0.1762,
      //         y: 0.0324,
      //         level: 1,
      //         page: 5,
      //       ),
      //     ),
      //     MilestoneModel(
      //         asset: ml1,
      //         width: 0.1177,
      //         height: 0.0824,
      //         x: 0.43,
      //         y: 0.1528,
      //         page: 5,
      //         level: 1,
      //         animType: "NONE",
      //         assetType: "SVG",
      //         description:
      //             "Watch Walkthrough and win 100 Tokens to get started!",
      //         rewards: [
      //           Reward(value: 100, type: "FLC"),
      //         ],
      //         actionUri: "/walkthrough",
      //         isCompleted: true),
      //     MilestoneModel(
      //       asset: ml2,
      //       width: 0.1491,
      //       height: 0.0816,
      //       x: 0.348,
      //       y: 0.3966,
      //       page: 5,
      //       level: 1,
      //       animType: "FLOAT",
      //       assetType: "SVG",
      //       description: "Complete your profile and get 200 Tokens and ₹50",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/profile",
      //       shadow: MilestoneShadowModel(
      //         asset: mls2,
      //         width: 0.1225,
      //         height: 0.0308,
      //         x: 0.3616,
      //         y: 0.3877,
      //         level: 1,
      //         page: 5,
      //       ),
      //     ),
      //     MilestoneModel(
      //       asset: ml3,
      //       width: 0.1158,
      //       height: 0.094,
      //       x: 0.704,
      //       y: 0.5673,
      //       page: 5,
      //       level: 1,
      //       animType: "FLOAT",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/profile",
      //     ),
      //     MilestoneModel(
      //       asset: ml4,
      //       width: 0.1107,
      //       height: 0.0591,
      //       x: 0.2795,
      //       y: 0.707,
      //       page: 5,
      //       level: 1,
      //       animType: "ROTATE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls4,
      //         width: 0.0775,
      //         height: 0.0327,
      //         x: 0.2692,
      //         y: 0.6939,
      //         level: 1,
      //         page: 5,
      //       ),
      //     ),
      //     MilestoneModel(
      //       asset: ml5,
      //       width: 0.1573,
      //       height: 0.0801,
      //       x: 0.0826,
      //       y: 0.8397,
      //       page: 5,
      //       level: 1,
      //       animType: "NONE",
      //       assetType: "SVG",
      //       description: "Do some task",
      //       rewards: [
      //         Reward(value: 200, type: "FLC"),
      //         Reward(value: 50, type: "Money"),
      //       ],
      //       actionUri: "/task",
      //       shadow: MilestoneShadowModel(
      //         asset: mls5,
      //         width: 0.1513,
      //         height: 0.0403,
      //         x: 0.08,
      //         y: 0.8291,
      //         level: 1,
      //         page: 5,
      //       ),
      //     ),
      //   ],
      // )
    ];
