import 'package:felloapp/base_util.dart';
import 'package:felloapp/core/constants/apis_path_constants.dart';
import 'package:felloapp/core/ops/augmont_ops.dart';
import 'package:felloapp/core/ops/db_ops.dart';
import 'package:felloapp/core/repository/banking_repo.dart';
import 'package:felloapp/core/repository/campaigns_repo.dart';
import 'package:felloapp/core/repository/coupons_repo.dart';
import 'package:felloapp/core/repository/games_repo.dart';
import 'package:felloapp/core/repository/getters_repo.dart';
import 'package:felloapp/core/repository/internal_ops_repo.dart';
import 'package:felloapp/core/repository/investment_actions_repo.dart';
import 'package:felloapp/core/repository/journey_repo.dart';
import 'package:felloapp/core/repository/lendbox_repo.dart';
import 'package:felloapp/core/repository/payment_repo.dart';
import 'package:felloapp/core/repository/paytm_repo.dart';
import 'package:felloapp/core/repository/prizing_repo.dart';
import 'package:felloapp/core/repository/referral_repo.dart';
import 'package:felloapp/core/repository/save_repo.dart';
import 'package:felloapp/core/repository/scratch_card_repo.dart';
import 'package:felloapp/core/repository/subcription_repo.dart';
import 'package:felloapp/core/repository/ticket_repo.dart';
import 'package:felloapp/core/repository/transactions_history_repo.dart';
import 'package:felloapp/core/repository/user_repo.dart';
import 'package:felloapp/core/repository/user_stats_repo.dart';
import 'package:felloapp/core/service/analytics/analyticsProperties.dart';
import 'package:felloapp/core/service/analytics/analytics_service.dart';
import 'package:felloapp/core/service/analytics/mixpanel_analytics.dart';
import 'package:felloapp/core/service/analytics/webengage_analytics.dart';
import 'package:felloapp/core/service/api.dart';
import 'package:felloapp/core/service/fcm/fcm_handler_datapayload.dart';
import 'package:felloapp/core/service/fcm/fcm_handler_service.dart';
import 'package:felloapp/core/service/fcm/fcm_listener_service.dart';
import 'package:felloapp/core/service/journey_service.dart';
import 'package:felloapp/core/service/lcl_db_api.dart';
import 'package:felloapp/core/service/notifier_services/connectivity_service.dart';
import 'package:felloapp/core/service/notifier_services/google_sign_in_service.dart';
import 'package:felloapp/core/service/notifier_services/internal_ops_service.dart';
import 'package:felloapp/core/service/notifier_services/leaderboard_service.dart';
import 'package:felloapp/core/service/notifier_services/marketing_event_handler_service.dart';
import 'package:felloapp/core/service/notifier_services/prize_service.dart';
import 'package:felloapp/core/service/notifier_services/scratch_card_service.dart';
import 'package:felloapp/core/service/notifier_services/tambola_service.dart';
import 'package:felloapp/core/service/notifier_services/transaction_history_service.dart';
import 'package:felloapp/core/service/notifier_services/user_coin_service.dart';
import 'package:felloapp/core/service/notifier_services/user_service.dart';
import 'package:felloapp/core/service/notifier_services/winners_service.dart';
import 'package:felloapp/core/service/payments/augmont_transaction_service.dart';
import 'package:felloapp/core/service/payments/bank_and_pan_service.dart';
import 'package:felloapp/core/service/payments/lendbox_transaction_service.dart';
import 'package:felloapp/core/service/payments/paytm_service.dart';
import 'package:felloapp/core/service/payments/razorpay_service.dart';
import 'package:felloapp/core/service/referral_service.dart';
import 'package:felloapp/navigator/app_state.dart';
import 'package:felloapp/navigator/back_button_actions.dart';
import 'package:felloapp/ui/elements/coin_bar/coin_bar_vm.dart';
import 'package:felloapp/ui/elements/faq_card/faq_card_vm.dart';
import 'package:felloapp/ui/elements/tambola_card/tambola_card_vm.dart';
import 'package:felloapp/ui/pages/campaigns/info_stories/info_stories_vm.dart';
import 'package:felloapp/ui/pages/campaigns/topSavers/top_saver_vm.dart';
import 'package:felloapp/ui/pages/finance/augmont/gold_buy/augmont_buy_vm.dart';
import 'package:felloapp/ui/pages/finance/augmont/gold_sell/gold_sell_vm.dart';
import 'package:felloapp/ui/pages/finance/autopay/autopay_process/autopay_process_vm.dart';
import 'package:felloapp/ui/pages/finance/autopay/user_autopay_details/user_autopay_details_vm.dart';
import 'package:felloapp/ui/pages/finance/lendbox/deposit/lendbox_buy_vm.dart';
import 'package:felloapp/ui/pages/finance/lendbox/withdrawal/lendbox_withdrawal_vm.dart';
import 'package:felloapp/ui/pages/finance/mini_trans_card/mini_trans_card_vm.dart';
import 'package:felloapp/ui/pages/finance/transactions_history/transaction_history_vm.dart';
import 'package:felloapp/ui/pages/games/tambola/dailyPicksDraw/dailyPicksDraw_viewModel.dart';
import 'package:felloapp/ui/pages/games/tambola/tambola_home/tambola_home_vm.dart';
import 'package:felloapp/ui/pages/games/tambola/tambola_widgets/picks_card/picks_card_vm.dart';
import 'package:felloapp/ui/pages/games/web/web_game/web_game_vm.dart';
import 'package:felloapp/ui/pages/games/web/web_home/web_home_vm.dart';
import 'package:felloapp/ui/pages/hometabs/journey/components/journey_banners/journey_banners_vm.dart';
import 'package:felloapp/ui/pages/hometabs/journey/components/source_adaptive_asset/source_adaptive_asset.vm.dart';
import 'package:felloapp/ui/pages/hometabs/journey/journey_vm.dart';
import 'package:felloapp/ui/pages/hometabs/play/play_viewModel.dart';
import 'package:felloapp/ui/pages/hometabs/save/save_viewModel.dart';
import 'package:felloapp/ui/pages/hometabs/win/win_viewModel.dart';
import 'package:felloapp/ui/pages/login/login_controller_vm.dart';
import 'package:felloapp/ui/pages/login/screens/mobile_input/mobile_input_vm.dart';
import 'package:felloapp/ui/pages/login/screens/name_input/name_input_vm.dart';
import 'package:felloapp/ui/pages/login/screens/otp_input/otp_input_vm.dart';
import 'package:felloapp/ui/pages/notifications/notifications_vm.dart';
import 'package:felloapp/ui/pages/onboarding/onboarding_main/onboarding_main_vm.dart';
import 'package:felloapp/ui/pages/rewards/detailed_scratch_card/gt_detailed_vm.dart';
import 'package:felloapp/ui/pages/rewards/instant_scratch_card/gt_instant_vm.dart';
import 'package:felloapp/ui/pages/rewards/multiple_scratch_cards/multiple_scratch_cards_vm.dart';
import 'package:felloapp/ui/pages/root/root_controller.dart';
import 'package:felloapp/ui/pages/root/root_vm.dart';
import 'package:felloapp/ui/pages/splash/splash_vm.dart';
import 'package:felloapp/ui/pages/support/faq/faq_page_vm.dart';
import 'package:felloapp/ui/pages/userProfile/bank_details/bank_details_vm.dart';
import 'package:felloapp/ui/pages/userProfile/kyc_details/kyc_details_vm.dart';
import 'package:felloapp/ui/pages/userProfile/my_winnings/my_winnings_vm.dart';
import 'package:felloapp/ui/pages/userProfile/referrals/referral_details/referral_details_vm.dart';
import 'package:felloapp/ui/pages/userProfile/settings/settings_vm.dart';
import 'package:felloapp/ui/pages/userProfile/userProfile/userProfile_viewModel.dart';
import 'package:felloapp/ui/service_elements/auto_save_card/subscription_card_vm.dart';
import 'package:felloapp/util/custom_logger.dart';
import 'package:felloapp/util/localization/generated/l10n.dart';
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../core/service/analytics/appflyer_analytics.dart';

GetIt locator = GetIt.instance;

Future<void> setupLocator() async {
  //Utils
  locator.registerLazySingleton(() => CustomLogger());
  locator.registerLazySingleton(() => ApiPath());
  locator.registerLazySingleton(() => S());

  //Services
  locator.registerLazySingleton(() => Api());
  locator.registerLazySingleton(() => LocalApi());
  locator.registerLazySingleton(() => FcmHandlerDataPayloads());
  locator.registerLazySingleton(() => FcmHandler());
  locator.registerLazySingleton(() => FcmListener(locator()));

  locator.registerLazySingleton(() => PaytmService());

  locator.registerLazySingleton(() => AnalyticsProperties());
  locator.registerLazySingleton(() => AnalyticsService());
  locator.registerLazySingleton(() => MixpanelAnalytics());
  locator.registerLazySingleton(() => WebEngageAnalytics());
  locator.registerLazySingleton(() => AppFlyerAnalytics());

  locator.registerLazySingleton(() => InternalOpsService());
  locator.registerLazySingleton(() => BankAndPanService());
  locator.registerLazySingleton(() => ReferralService());
  locator.registerLazySingleton(() => BackButtonActions());
  //Model Services
  locator.registerLazySingleton(() => BaseUtil());
  locator.registerLazySingleton(() => AppState());
  locator.registerLazySingleton(() => ConnectivityService());
  locator.registerLazySingleton(() => UserService());
  locator.registerLazySingleton(() => UserCoinService());
  locator.registerLazySingleton(() => AugmontTransactionService());
  locator.registerLazySingleton(() => LendboxTransactionService());
  locator.registerLazySingleton(() => TxnHistoryService());
  locator.registerLazySingleton(() => TambolaService());
  locator.registerLazySingleton(() => PrizeService());
  locator.registerLazySingleton(() => WinnerService());
  locator.registerLazySingleton(() => LeaderboardService());
  locator.registerLazySingleton(() => ScratchCardService());
  locator.registerLazySingleton(() => JourneyService());
  locator.registerLazySingleton(() => GoogleSignInService());
  locator.registerLazySingleton(() => RazorpayService());
  locator.registerSingletonAsync(() => SharedPreferences.getInstance());
  locator.registerLazySingleton(() => MarketingEventHandlerService());

  //Repository
  locator.registerLazySingleton(() => DBModel());
  // locator.registerLazySingleton(() => LocalDBModel());
  locator.registerLazySingleton(() => AugmontService());
  locator.registerLazySingleton(() => UserRepository());
  locator.registerLazySingleton(() => TambolaRepo());
  locator.registerLazySingleton(() => InvestmentActionsRepository());
  locator.registerLazySingleton(() => BankingRepository());
  locator.registerLazySingleton(() => CouponRepository());
  locator.registerLazySingleton(() => PaytmRepository());
  locator.registerLazySingleton(() => JourneyRepository());
  locator.registerLazySingleton(() => GameRepo());
  locator.registerLazySingleton(() => ReferralRepo());
  locator.registerLazySingleton(() => ScratchCardRepository());
  locator.registerLazySingleton(() => TransactionHistoryRepository());
  locator.registerLazySingleton(() => GetterRepository());
  locator.registerLazySingleton(() => InternalOpsRepository());
  locator.registerLazySingleton(() => PaymentRepository());
  locator.registerLazySingleton(() => SubscriptionRepo());
  locator.registerLazySingleton(() => SaveRepo());
  locator.registerLazySingleton(() => LendboxRepo());
  locator.registerLazySingleton(() => PrizingRepo());
  locator.registerLazySingleton(() => UserStatsRepo());
  locator.registerLazySingleton(() => RootController());
  // SPLASH
  locator.registerFactory(() => LauncherViewModel());
  locator.registerFactory(() => RootViewModel());
  // Hometabs
  locator.registerFactory(() => PlayViewModel());
  locator.registerFactory(() => SaveViewModel());
  locator.registerFactory(() => WinViewModel());
  locator.registerFactory(() => JourneyPageViewModel());

  // VIEW MODELS
  locator.registerFactory(() => TransactionsHistoryViewModel());
  locator.registerFactory(() => LoginControllerViewModel());
  locator.registerFactory(() => LoginNameInputViewModel());
  locator.registerFactory(() => LoginOtpViewModel());
  locator.registerFactory(() => LoginMobileViewModel());
  locator.registerFactory(() => DailyPicksDrawViewModel());
  locator.registerFactory(() => UserProfileVM());
  locator.registerFactory(() => KYCDetailsViewModel());
  locator.registerFactory(() => BankDetailsViewModel());
  locator.registerFactory(() => GoldBuyViewModel());
  locator.registerFactory(() => GoldSellViewModel());
  locator.registerFactory(() => TambolaHomeViewModel());
  // locator.registerFactory(() => TambolaGameViewModel());
  locator.registerFactory(() => WebHomeViewModel());
  // locator.registerFactory(() => RewardLeaderboardViewModel());
  locator.registerFactory(() => WebGameViewModel());
  locator.registerFactory(() => PicksCardViewModel());
  locator.registerFactory(() => ReferralDetailsViewModel());
  locator.registerFactory(() => MyWinningsViewModel());
  locator.registerFactory(() => NotificationsViewModel());
  locator.registerFactory(() => GTDetailedViewModel());
  locator.registerFactory(() => GTInstantViewModel());
  locator.registerFactory(() => MultipleScratchCardsViewModel());
  locator.registerFactory(() => TopSaverViewModel());
  locator.registerFactory(() => AutosaveProcessViewModel());
  locator.registerFactory(() => UserAutosaveDetailsViewModel());
  locator.registerFactory(() => CampaignRepo());
  locator.registerFactory(() => OnboardingViewModel());
  locator.registerFactory(() => JourneyBannersViewModel());
  locator.registerFactory(() => FaqPageViewModel());
  locator.registerFactory(() => LendboxBuyViewModel());
  locator.registerFactory(() => LendboxWithdrawalViewModel());
  locator.registerFactory(() => InfoStoriesViewModel());
  locator.registerFactory(() => SettingsViewModel());

  //WIDGETS
  locator.registerFactory(() => MiniTransactionCardViewModel());
  locator.registerFactory(() => FelloCoinBarViewModel());
  locator.registerFactory(() => FAQCardViewModel());
  locator.registerFactory(() => SourceAdaptiveAssetViewModel());
  locator.registerFactory(() => SubscriptionCardViewModel());
  locator.registerFactory(() => TambolaCardModel());
  // locator.registerFactory<UsernameInputViewModel>(() => UsernameInputViewModel());
  await locator.allReady();
}
