# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  before_all do
    increment_build_number
    # xctool #run the tests of your app
  end
  desc "Push a new release build to the App Store"
  lane :checkRelease do 
      Spaceship::ConnectAPI.login(
        use_portal: false,
        tunes_team_id: "7FH5SHLD2G",
      )
    
      app = Spaceship::ConnectAPI::App.find("in.fello.felloappiOS.dev"),
      if app.nil?
        UI.important "not found in team 7FH5SHLD2G on ASC!"
        next
      end
    
      if !app.reject_version_if_possible!(platform: Spaceship::ConnectAPI::Platform::IOS)
        UI.important "couldn't reject!"
        next
      end
  end

  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "dev")
    upload_to_app_store
  end
end


