# Update fastlane automatically
update_fastlane

default_platform(:android)

platform :android do
  desc "Build android aab and apk"
  lane :build_android do |options|
   
    # sh "./flutter_test.sh"
    # Build AAB
    sh "./flutter_build.sh --clean"
    # Build APK
    sh "./flutter_build.sh --apk"
  end

  desc "Deploy (Upload to play store)"
  lane :deploy_android do |options|
    upload_to_play_store(
      track: options[:production] ? 'production' : options[:internal] ? 'internal' : options[:alpha] ? 'alpha' : 'beta',
      aab: '../build/app/outputs/bundle/release/app.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end